### ISSUE TITLE
Disclaimer and landing page for clin.iobio

### ISSUE THREAD

**Issue by mvelinder** [iobio/clin.iobio#119]

**Comment by adityaekawade** [comment]
Just following up on this. Do we have some content for Disclaimer? so I can add it and move this issue.

**Comment by tonydisera** [comment]
Hi @adityaekawade .  You can pull the disclaimer from stage.gene.iobio.io.  It is under the "more" menu.  Also, you may want to copy what will has done for "terms".  You will find that under the "note" icon in the nav menu.
