### ISSUE TITLE
Phenotypes, group select

### ISSUE THREAD

**Issue by mvelinder** [iobio/clin.iobio#121]
From Al -
Is there a way to group select? Under Hydrocephalus, there are 26 options. Should there be a way to select them all? Naively, I assumed clicking the checkbox in the gray title area would do that.
![image](https://user-images.githubusercontent.com/22081541/76648084-9cf84b00-6523-11ea-9b8d-8901938af289.png)

**Comment by adityaekawade** [comment]
From Al: 
There are three MPPH syndromes and one somatic and they appear under multiple headings, including Hydrocephalus and MPPH. Selecting the term under one heading updates the selection under the other. I wonder if this is intuitive?

**Comment by adityaekawade** [comment]
Group selection is a good idea, but I am not sure if we would want the users to select 26 options at one go. Some terms have 80+options.

I would like to know what you think?

**Comment by adityaekawade** [comment]
I did test it with running 23 options at one go, the app handles it fine. I guess the requests were completed within 3-4 minutes from the GTR server.
(screenshot is attached in this issue's description)

**Comment by AlistairNWard** [comment]
One potential solution would be to provide a warning to users. We could have a recommendation that users select no more than N (where N is something we thing reasonable, maybe 4?) results from GTR. We could include a counter at the top of the modal showing how many terms are currently selected, and when this exceeds N, we could include a clear warning stating our recommendation that they don't choose so many.

Another option would be to remove the checkbox in the top level of the GTR terms. I think my biggest usability issue is demonstrated in the following view (for mpph in GTR):

![Screen Shot 2020-03-17 at 11 29 18 AM](https://user-images.githubusercontent.com/523111/76872485-dc37dc00-6842-11ea-9c47-bac5f27a1496.png)

To a naive user, I don't know why I can't select Megalencephaly-..., but I can select all the other terms. It also somewhat hides the fact that there are other options for all the terms. You can figure out that the other terms, e.g. Hydrocephalus, occur in the list of terms, but it isn't obvious. It seems to me that behaviour should be the same for all terms, so we could do a couple of things (to discuss):

1. Remove the checkbox at the top level, and the user will have to open each top level term that seems relevant and select the terms they want.

2. Have a checkbox in the term title for all results, and this checkbox is a select all. A count of the number of selected terms is provided at the top of the modal, and the user is encouraged (with warnings) to keep this number small.

Thoughts?

**Comment by tonydisera** [comment]
I favor option #2.  This will avoid the tiresome action of having to expand in order to any selection.  If they check this we can prompt ("Only 20 conditions can be selected at one.  Do you want to continue by selecting the first 20 out of 77?"  continue cancel)

**Comment by mvelinder** [comment]
Wouldn't selecting 20+ conditions almost surely break GTR or even if it worked the user would be sitting there for multiple minutes?

**Comment by adityaekawade** [comment]
Yeah, we can show count at the top and provide a warning if it exceeds that count. 
Out of the two options suggested, I would prefer option 1 (remove the checkbox at the top level). 

If the user does a select all and it selects 80 conditions, and we have a limit of 10, then they have to open the expansion panel and deselect 70 of them. It also limits the number of distinct conditions that they might select. 
Example: 
The user selects "Hydrocephalus". 26 options are selected by default. He opens the expansion panel and unchecks 16. 
Next, he selects "Megalencephaly", which adds another 11 to his list, There are 21 conditions selected, and he has not even gone past two items.

**Comment by AlistairNWard** [comment]
My devils advocate against option 2 would be that if we want to more than encourage users to limit the number of terms, and actually make it difficult to select too many, we would surely want to encourage them to review all terms carefully to pick the handful of most relevant terms. That would argue for option 1.

**Comment by mvelinder** [comment]
From our Zoom call today:

- Add total number of terms selected in top bar
- Add wording to encourage submitting 5 terms or less, prompt user when more than 5 terms have been selected, allow them to continue to submit more than 5 terms, but also warn that it might take a few minutes
- Remove "generic" term checkboxes from lists so none of the expandable trees have checkboxes next to them, this will make the user expand the tree of terms to select the generic term, but make sure the generic term is at the TOP of the list

**Comment by adityaekawade** [comment]
I have added the count as a badge that shows at the top for each tool and removed the checkboxes. 
It also shows the warning when 5 or more conditions are selected. @mvelinder Pls check the wordings and if the background color of the alert notification is okay before I commit my changes, 


<img width="973" alt="Screen Shot 2020-03-19 at 4 10 44 PM" src="https://user-images.githubusercontent.com/16284713/77123101-71ca9b80-69fc-11ea-930e-cf3d04b712fe.png">

**Comment by mvelinder** [comment]
I don't see these changes on stage.clin.iobio. Are they somewhere else to test?

**Comment by adityaekawade** [comment]
You can test it on dev.clin.iobio.io.

**Comment by tonydisera** [comment]
2 pull requests were assigned to me yesterday for clin.iobio #128, #139.  I though the new procedure was that if a pull request is assigned to a person, they need to verify and merge the pull request if it looks good.   Then the merged changes will be deployed to http://clin.iobio.io

**Comment by tonydisera** [comment]
I will try to verify these pull requests this morning.

**Comment by tonydisera** [comment]
Actually, this is pretty confusing.  I see 2 pull requests for issues #138, #139.  I think Issue #121 might be piggy backed on #139.   If all of the pull requests are going through me, this is going to be a time sink if this isn't well organized.  I should be able to merge a pull request, look at a single issue and verify.

**Comment by tonydisera** [comment]
For now, I'm going to just blindly merge the pull requests.  I don't want to spend the next hour  trying to figure this out.

**Comment by tonydisera** [comment]
Please disregard my comments a few minutes ago.  I see 3 issues in 'Read to Review' .  I'll move my question to Slack.

**Comment by tonydisera** [comment]
I feel like we have made it easier for the software developer, but harder for the user.  Now I have to expand every element where I think I want to select that term.  It seems like since we were able to move the 'matched' term to the top of the list, it would have been easy to have a checkbox for that 'default' term.  I'll merge the pull request, but in my opinion, we have taken a step in the wrong direction.

<img width="998" alt="Screen Shot 2020-03-21 at 11 21 35 AM" src="https://user-images.githubusercontent.com/8420103/77232385-5a0f2680-6b66-11ea-9b35-43e79ce71f21.png">

**Comment by tonydisera** [comment]
Another minor comment - I think we should decrease the padding between the checkbox and the term.   Also, it would be nice if I could click on the term or the checkbox to select the term.
<img width="960" alt="Screen Shot 2020-03-21 at 11 44 39 AM" src="https://user-images.githubusercontent.com/8420103/77232949-c2133c00-6b69-11ea-8fc0-fdc75fde9db8.png">

**Comment by AlistairNWard** [comment]
Hey @tonydisera, we discussed this on Friday. I really didn't like the fact that some terms had a checkbox at the top level and some didn't. It was very unclear to a user why they had to open the full list for some terms and not others.

Next, we are trying to force users to only pick a very small number of terms from a potentially very large number. As such, it seemed prudent to ensure that users take the time to look at the available terms and select the couple of terms that are most relevant. The 'matched' term will always be the first one, but this way, the user will see if there is something more relevant to them than this term. For example, the entered term may be X, but in the full list, there is an "X, recessive", and "X, dominant". If the clinician knows this is dominant, they would be better choosing "X, dominant", but they would never have known without looking at all the terms.

Again - happy to discuss more.

**Comment by tonydisera** [comment]
Sorry.  I was in a foul mood yesterday.  You make a strong argument for this new selection behavior.  And I also need to remind myself that this this user action of selecting terms should do with care and that it likely won't be frequent operation.  Sorry for second guessing the direction.

**Comment by AlistairNWard** [comment]
@mvelinder @adityaekawade Good to go
