### ISSUE TITLE
Remove all AWS dynamodb, signin dependencies.

### ISSUE THREAD

**Issue by mvelinder** [iobio/clin.iobio#124]

**Comment by adityaekawade** [comment]
When clin.iobio is launched from Mosaic, the user is authenticated and AWS dynamo DB, sign in dependency is not required. But in the future, if we allow users to import their files and run Clin.iobio in standalone mode and not just with demo data, we might require authentication and sign-in functionality. So thinking about that does it make sense to retain this dependency that can be used in the future? 
@mvelinder @tonydisera

**Comment by tonydisera** [comment]
We would probably have to re-work this from the ground-up.  Perhaps you can keep a branch of this code and then remove it from the dev branch.

**Comment by adityaekawade** [comment]
Yes, that sounds good.

**Comment by mvelinder** [comment]
Assuming this is good, as I can't test it
