### ISSUE TITLE
Scroll position is kept the same across GTR/Phenolyzer/HPO, should return to top

### ISSUE THREAD

**Issue by mvelinder** [iobio/clin.iobio#129]
Scroll position is kept the same across GTR/Phenolyzer/HPO. It should return to the top. When you go Phenolyzer you don't know you're in the middle of the list and there are terms above your current position.

Especially insidious if you have scroll bars auto hiding like on Mac. I'm using dark theme here to highlight the positions

![image](https://user-images.githubusercontent.com/22081541/76769117-9fe07f00-6761-11ea-9950-c0705e7a804a.png)
![image](https://user-images.githubusercontent.com/22081541/76769133-a66ef680-6761-11ea-85da-4033e36f577a.png)

**Comment by AlistairNWard** [comment]
@mvelinder @adityaekawade This looks fixed to me, so I'm happy for this to be merged.
