### ISSUE TITLE
Change remove gene "Agree" to "Yes"

### ISSUE THREAD

**Issue by mvelinder** [iobio/clin.iobio#130]
![image](https://user-images.githubusercontent.com/22081541/76771352-d8ce2300-6764-11ea-98f0-d6fa3af6ba94.png)

**Comment by adityaekawade** [comment]
@mvelinder is this safe to be moved to the next column?

**Comment by AlistairNWard** [comment]
Going to move this back with a couple of questions of style @mvelinder @tonydisera @adityaekawade 

1. This has been fixed as asked, but should the options be Cancel and Yes, or just Yes and No?
2. It can be unclear how to delete a gene. You only see the option on hover, and then only when you hover over the gene name. If you hover anywhere else on the row, the X doesn't appear.

Should we just have the delete option always visible? Or an actions column where there could be links to resources, and the option to delete?

**Comment by mvelinder** [comment]
I agree isn't' somewhat hidden. We didn't want to show the (x) by default, but showing it on hovering anywhere in the row is probably better than the current hover only on the gene name

**Comment by AlistairNWard** [comment]
What was the reason for not showing by default? I always question hiding features like this. If we think deleting a gene is a reasonable action, it should be clear to a user they can do it. It seems to me that you either have the delete always visible, e.g. github labels:

![Screen Shot 2020-03-23 at 4 11 02 PM](https://user-images.githubusercontent.com/523111/77358898-190f4180-6d21-11ea-8535-501bf920ef95.png)

or you have group actions that can be applied to all genes:

![Screen Shot 2020-03-23 at 4 11 25 PM](https://user-images.githubusercontent.com/523111/77358907-1dd3f580-6d21-11ea-96fe-1e11258d212c.png)

Having information appearing on hover makes sense, but hiding actions in a hover doesn't seem like good practice to me.

**Comment by adityaekawade** [comment]
I agree that it is not very obvious. If I remember correctly these were two points for having the delete icon on mouseover: 

1.  A horizontal scroll was being added in the genes table for the “actions” column if the name of the condition/ phenotype was big (eg. Megalencephaly-Polymicrogyria-Polydactyly-Hydrocephalus syndrome). 
2.  It was thought that only a few users might want to delete a gene from the table, hence it is not required to be shown by default. 



> should the options be Cancel and Yes, or just Yes and No?


“Yes” and “No” compliments each other better than “Cancel” and “Yes”

**Comment by AlistairNWard** [comment]
I will create a new issue regarding deleting a gene. This isn't connected to this original issue (so I shouldn't have added it here), and solving this can be a discussion and isn't necessary as a priority. So, for this issue - stick to the Yes/No.

**Comment by adityaekawade** [comment]
Changed the wording to "No" from "Cancel" 
<img width="388" alt="Screen Shot 2020-03-23 at 5 17 18 PM" src="https://user-images.githubusercontent.com/16284713/77375263-3563ac00-6d2a-11ea-8570-8d4fcd6b1c22.png">
Test: http://dev.clin.iobio.io/

**Comment by AlistairNWard** [comment]
@adityaekawade @mvelinder Can close
