### ISSUE TITLE
Gene Associations not working

### ISSUE THREAD

**Issue by mvelinder** [iobio/clin.iobio#131]
Gene Associations not showing up in Review Variants step. PRX should be showing multiple associations here
![image](https://user-images.githubusercontent.com/22081541/76791136-d62ff580-6785-11ea-96f6-6946ee4ef9f0.png)
![image](https://user-images.githubusercontent.com/22081541/76791199-f5c71e00-6785-11ea-8a19-7743d4095fea.png)

**Comment by adityaekawade** [comment]
Hi @tonydisera , I just wanted to check with you if anything changed regarding the "Gene association" after the new update of gene.iobio. 
I tested with an old version of gene locally and it seems to be showing the associations. 

<img width="1366" alt="Screen Shot 2020-03-18 at 8 25 37 PM" src="https://user-images.githubusercontent.com/16284713/77028828-332ed580-6957-11ea-867c-b94ae145c7ab.png">

**Comment by mvelinder** [comment]
Likely need to investigate this in the gene.iobio code.

Possible way to reproduce this by going to Review Variants first and then back to Review Phenotypes. But also happens when doing through the normal ordering. Need to investigate further and do rigorous testing @adityaekawade will be leading this

**Comment by adityaekawade** [comment]
I am still debugging this issue. But I have found a way to reproduce this bug and show the associated genes in review variants. 

- launch clin.iobio
- wait for a while to complete printing "No matrix value to map to compoundHet for inheritance" in the console. (It needs to be printed at least 8 times. sometimes it prints just 2 times and this process fails) 
- Considering the above statement is printed, generate gene list in step 2
- Move to "review variants" tab 
- the associated genes should now be seen  

See the screenshot for reference. 
<img width="1632" alt="Screen Shot 2020-04-01 at 3 19 04 PM" src="https://user-images.githubusercontent.com/16284713/78193132-a3952680-742e-11ea-80ca-b1c586d1450a.png">


The above statement is printed from the method `setFeaturesForVariants()` in gene.iobio. I am still trying a better approach to debug this issue, but I wanted to know what does "No matrix value to map" implies and if it is printed to show success or some failure in the `setFeaturesForVariants`? 

@tonydisera @mvelinder

**Comment by adityaekawade** [comment]
The bug is fixed if I delete the highlighted code from `applyGenesClin` function (refer screenshot)  in gene.iobio.

<img width="1119" alt="Screen Shot 2020-04-01 at 5 42 00 PM" src="https://user-images.githubusercontent.com/16284713/78199301-2377bc80-7440-11ea-917a-d6201f77aaf4.png">

Tony, Is there any side effect for removing the above lines of code?

**Comment by mvelinder** [comment]
Mentioning @tonydisera for thoughts on the above comment by @adityaekawade

**Comment by tonydisera** [comment]
I am not sure. Is this in GeneHome?

**Comment by adityaekawade** [comment]
Yes, this is in `GeneHome.vue`. The function `applyGenesClin` is called when gene receives clin message and clinObject type is 'apply-genes'.

**Comment by tonydisera** [comment]
Yes, that looks like it might be causing the problem.  To verify, you will need to also save an analysis and launch clin from the Utah Mosaic Analysis 'Analyses' tab to make sure that that removing that code doesn't cause any side effects.

**Comment by adityaekawade** [comment]
Following pull request should fix this issue: https://github.com/iobio/gene.iobio.vue/pull/424
