### ISSUE TITLE
Landing page text

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/clin.iobio#132]
Minor issue that people are welcome to disagree with, but I think we could simplify the text a little:

"clin.iobio makes it easy to review sequencing and case metrics, generate a prioritized list of genes associated with the disease/phenotype, review candidate variants, and generate a report of your findings"

The workflow steps should have the same wording as in the app. The title (at the right of the screen in the scroll area) is consistent with the app, but the left scrollable menu is not. Use "Review case", "Review Phenotypes", "Review variants", "Report findings". Should the workflow in the app itself have "Report findings as the final step? Seems like we want to get report in there.

The "Review variants" text could be improved, imo. Not a fan of starting sentences with "And"!! Maybe more like:

"Review and attach significance to candidate variants. Promote collaboration by adding notes for colleagues"

**Comment by adityaekawade** [comment]
The wording on the left menu was changed because it seemed the word "Review" was used too often. 

I vote for "Report findings" instead of just "finding" as the final step.

**Comment by mvelinder** [comment]
My vote would be:

Review case
Select phenotypes
Investigate variants
Report findings

Agree @AlistairNWard ?

**Comment by AlistairNWard** [comment]
Sounds fine to me. Is two instances of review too many? Review variants seems reasonable (and doesn't appear next to Review case). Also the action the user takes (e.g. the name of the button) on the variants page is Review (to assign a significance), and variants are classified as not reviewed until this has taken place.

**Comment by mvelinder** [comment]
@adityaekawade I see this is updated on landing page, but not on the actual workflow text 
![image](https://user-images.githubusercontent.com/22081541/77943279-350f6780-727a-11ea-91e6-fb0e6bb6a471.png)
We need to change it there too

**Comment by mvelinder** [comment]
@adityaekawade it sounds like we agree on:

Review case
Select phenotypes
Review variants
Report findings

We need to update the text here:
![image](https://user-images.githubusercontent.com/22081541/77943463-7c95f380-727a-11ea-8631-d3fb4d48513a.png)
and here
![image](https://user-images.githubusercontent.com/22081541/77943481-83bd0180-727a-11ea-96ee-c341c895df57.png)
to reflect these wordings

**Comment by adityaekawade** [comment]
I will update this section as well to reflect these wordings. 
<img width="487" alt="Screen Shot 2020-03-30 at 2 17 05 PM" src="https://user-images.githubusercontent.com/16284713/77962819-2c765b80-7291-11ea-82f2-3060b79ed5e8.png">

**Comment by tonydisera** [comment]
It looks like the landing page text is still out-of-sync.

<img width="995" alt="Screen Shot 2020-03-30 at 7 41 57 PM" src="https://user-images.githubusercontent.com/8420103/77978220-b557bc00-72be-11ea-966e-b14108fd4b88.png">

**Comment by adityaekawade** [comment]
Is this on stage.clin? Staging is not updated yet. 
#154 should fix this.

**Comment by AlistairNWard** [comment]
I'm happy with this
