### ISSUE TITLE
Expected coverage does nothing

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/clin.iobio#133]
On the review case tab, I have the opportunity to input the expected coverage, but doing so changes nothing. I assumed that the coverage charts would be updated with the cutoff being what I entered.

![Screen Shot 2020-03-16 at 4 44 40 PM](https://user-images.githubusercontent.com/523111/76798173-75b0b080-67a5-11ea-80b6-bef0488fca04.png)

**Comment by AlistairNWard** [comment]
Ok, I just noticed that it does something, but only when I hover over the checkmark. This is not intuitive to me. If you have the ability to change the setting, we should be able to see an effect immediately. I would propose always showing the cutoff, unless no expected value is provided.

**Comment by adityaekawade** [comment]
It also shows failed QC if the expected coverage entered is greater than the Median coverage value. 
<img width="1076" alt="Screen Shot 2020-03-23 at 2 17 34 PM" src="https://user-images.githubusercontent.com/16284713/77364428-a5196d00-6d11-11ea-9add-a39ea4df622b.png">

I am adding @WilliamRichards2017 to this discussion, who was working on this issue.

**Comment by WilliamRichards2017** [comment]
I can have the min coverage flash for several seconds on page load and whenever the coverage is updated to alert the users of its existence, and/or have some notice appear next to the coverage icon on page load saying that the user can hover to view the coverage.  @AlistairNWard Would you prefer showing coverage by default, or the min-coverage flashing with some notice to hover

**Comment by AlistairNWard** [comment]
In my opinion, I'm not sure why we're not just showing the threshold all the time. The visual representation of the coverage distribution seems like the perfect medium to show all the pertinent information in one place, and it isn't overloaded with information, so I don't see the benefit of hiding the coverage threshold in a hover.

**Comment by AlistairNWard** [comment]
Happy with that
