### ISSUE TITLE
Project title is clickable, but does nothing

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/clin.iobio#134]
In the title bar, the project title (Demo Platinum) is a button that can be clicked, but doing so doesn't do anything

**Comment by adityaekawade** [comment]
I will make the project title just a text instead of a clickable button. Or was it intended to show a tooltip to display some information?  
@AlistairNWard

**Comment by mvelinder** [comment]
We should try to make this a clickable tooltip that displays a brief summary of the project, including: the project description, pedigree and a summary of the data quality? Will might be able to help with this.

**Comment by mvelinder** [comment]
I'd say just do 1) project description 2) a single pedigree for the whole project/family 3) median read coverage across the entire project

**Comment by AlistairNWard** [comment]
I would say read coverage is overkill. Personally, I would limit the information in this to information that is relevant across the whole app, and isn't otherwise available in all steps. So, I would stick to the project description / clinical presentation.

The pedigree and coverage is useful in the case, and variant review and findings and is available in all of them anyway (gene shows the pedigree for inheritance, and coverage for variants) - so I don't think we need to include those in the tooltip.

No need to overcomplicate - just the clinical description, imo

**Comment by mvelinder** [comment]
I'd agree we can toss read coverage. But I'd vote to keep the pedigree. Nice reminder/reference for the family structure. If there is an additional sibling let's say.

Agreement then for:

1. project/clinical description
2. single pedigree image

??

**Comment by AlistairNWard** [comment]
I'm not going to argue the point, but I don't really agree with having the pedigree. You can see it in gene and that's the only other place it's useful. But if other people like it there, that's fine.

**Comment by mvelinder** [comment]
Meh, I guess you do see it in gene. Although it's arguably a project-wide metric. And the view in gene is more related to the inheritance of that variant in the pedigree.

But it would probably be more clean with just the description.

I'll concede. Let's just do the project/clinical description text ONLY @WilliamRichards2017 . We can always add more there if people request it

**Comment by AlistairNWard** [comment]
Exactly. Let's get the quickest fit for purpose solutions in place. We can change our minds down the road

**Comment by AlistairNWard** [comment]
Now it does something!
