### ISSUE TITLE
Connected workflow

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/clin.iobio#135]
Is it weird that there are gaps in the workflow? Feels like they should be connected up.

![Screen Shot 2020-03-16 at 4 53 35 PM](https://user-images.githubusercontent.com/523111/76798839-beb53480-67a6-11ea-9ca9-12a94d9f6653.png)

**Comment by adityaekawade** [comment]
Workflow is now connected. 
<img width="1122" alt="Screen Shot 2020-03-18 at 11 29 52 PM" src="https://user-images.githubusercontent.com/16284713/77038229-777a9f80-6970-11ea-99e4-0284c4664396.png">

**Comment by adityaekawade** [comment]
@tonydisera This issue was also linked with the Pull Request #137 that you merged yesterday. If it is ok, we can move this issue to "Reviewer approved".

**Comment by tonydisera** [comment]
I see.  I didn't realize that when I was testing yesterday.  Can we have one issue per pull request moving forward?  I've already merged the pull request.  Does it look correct on your end?  If so, yes, go ahead and move it to 'reviewer approved'.

**Comment by AlistairNWard** [comment]
This is super minor, but before tasks are marked as complete, the joining line is thin and isn't centered vertically. When tasks are complete, the line thickens (all thickness appears below the thin line), and it now looks centered (sorry if that makes no sense). But the line should always be centered in the boxes.

![Screen Shot 2020-03-22 at 9 39 09 PM](https://user-images.githubusercontent.com/523111/77271717-c2085e80-6c85-11ea-929f-24a1b4dcf6c1.png)

**Comment by adityaekawade** [comment]
I have tried to make the lines centered. Can you check it @AlistairNWard 
It's deployed on http://dev.clin.iobio.io/

**Comment by AlistairNWard** [comment]
@adityaekawade. Looks perfect!
