### ISSUE TITLE
New filter modal appears behind title bar

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/clin.iobio#136]

**Comment by adityaekawade** [comment]
Hi @AlistairNWard , Can you add more details about this issue.

**Comment by AlistairNWard** [comment]
1. Go to review variants and let variants load
2. Click on +New Filter at the top left (above the Recessive title)
3. The Edit Filter modal opens, but the top of the modal is hidden behind the title bar

![Screen Shot 2020-03-25 at 3 00 11 PM](https://user-images.githubusercontent.com/523111/77575088-5dc5e480-6ea9-11ea-96f0-78a408162c36.png)

**Comment by adityaekawade** [comment]
Linked PR in gene.iobio repo: https://github.com/iobio/gene.iobio.vue/pull/397 
The issue will be fixed once this PR is merged and deployed.

**Comment by adityaekawade** [comment]
Ready to test on https://stage.clin.iobio.io/ 

@AlistairNWard @mvelinder

**Comment by AlistairNWard** [comment]
@adityaekawade Fixed for me

I added #151, which is associated with the modal (and doesn't affect gene.iobio)
