### ISSUE TITLE
Reviewed variant order

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/clin.iobio#141]
As you review variants, they move to the Reviewed category in the left menu. The variants are ordered in the same way as they originally appear in the left menu, but we might want to consider having all Significant variants at the top, then uncertain etc.

![Screen Shot 2020-03-22 at 9 37 58 PM](https://user-images.githubusercontent.com/523111/77271564-6d64e380-6c85-11ea-9db6-ce88655b7b44.png)

**Comment by WilliamRichards2017** [comment]
I can make sure that these are first sorted by significance!

**Comment by AlistairNWard** [comment]
Thanks Will

**Comment by WilliamRichards2017** [comment]
A pull request containing a fix for this was opened in gene.iobio at:
 https://github.com/iobio/gene.iobio.vue/pull/475

I have requested a review from @adityaekawade  !

**Comment by adityaekawade** [comment]
gene.iobio needs to be updated with this fix, before we can do a final review for this issue as stage.clin is pointing to prod gene.iobio now.

**Comment by mvelinder** [comment]
> gene.iobio needs to be updated with this fix, before we can do a final review for this issue as stage.clin is pointing to prod gene.iobio now.

Good point, who will do that fix? Can you do it Adit? Set up an issue and fix it on the gene repo?

**Comment by adityaekawade** [comment]
Tony suggested yesterday to point clin to stage.gene since we are doing a Utah release and not a public release. So I will point clin back to stage.gene and notify you when it is ready,

**Comment by adityaekawade** [comment]
Ready for final review! 
@mvelinder @AlistairNWard

**Comment by mvelinder** [comment]
Looks to be working as expected!
