### ISSUE TITLE
Point to new backend.iobio.io instead of nv-prod.iobio.io for standalone mode

### ISSUE THREAD

**Issue by tonydisera** [iobio/clin.iobio#149]
<img width="848" alt="Screen Shot 2020-03-27 at 10 22 26 AM" src="https://user-images.githubusercontent.com/8420103/77777345-0c3a6880-7015-11ea-8660-dcbb102541c9.png">

**Comment by mvelinder** [comment]
I'm not capable of testing this, but marking it as review complete
