### ISSUE TITLE
Modals become dissociated

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/clin.iobio#151]
1. Go to review variants, the click +New Filter at the top left
2. Open the consequence drop down and just keep adding more and more terms

The modal containing the consequence terms gets separated from the main model, which is odd!

![Screen Shot 2020-03-27 at 4 03 27 PM](https://user-images.githubusercontent.com/523111/77795926-c72e2a80-7044-11ea-9ab5-e5b1c660780a.png)

**Comment by adityaekawade** [comment]
@AlistairNWard, It looks like the functionality of "filters" is changed in gene.iobio and this modal is no longer shown. This makes the issue obsolete and we can probably close it. 
Ref issue: https://github.com/iobio/gene.iobio.vue/issues/406 
<img width="320" alt="Screen Shot 2020-04-07 at 12 41 22 PM" src="https://user-images.githubusercontent.com/16284713/78712234-243fa100-78cd-11ea-9c71-cd74b0d59215.png">

**Comment by AlistairNWard** [comment]
@adityaekawade Agreed, this is no longer relevant while filters are deactivated. But, we will be adding them back in, so would be good to keep this issue around to revisit when they're back. I've removed it from the milestone though.

**Comment by adityaekawade** [comment]
This issue has been addressed in the latest PR in the gene repo. 
Ref: https://github.com/iobio/gene.iobio.vue/pull/497

**Comment by AlistairNWard** [comment]
Fixed in clin because the option is no longer there.
