### ISSUE TITLE
Add Mother and Father tracks to "Other tracks", remove SFARI track

### ISSUE THREAD

**Issue by mvelinder** [iobio/clin.iobio#155]
![image](https://user-images.githubusercontent.com/22081541/77966402-318ed700-72a0-11ea-9453-7320474084fc.png)

**Comment by AlistairNWard** [comment]
Just keeping it in documented that the SFARI data isn't public, so the SFARI track should not be available to general users

**Comment by adityaekawade** [comment]
This issue is fixed by the following PR: https://github.com/iobio/gene.iobio.vue/pull/443
