### ISSUE TITLE
HPO terms are cleared on edit

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/clin.iobio#171]
1. Go to demo data, Select Phenotypes and select the first term for GTR, Phenolyzer and HPO.
2. Data is analyzed and we get genes
3. On Inputs, click Edit
4. In GTR and Phenolyzer, the first term is still selected, but HPO is blank. So if I just click Next through the whole thing, I retain terms from GTR and Phenolyzer, but HPO is blank. 
5. In the Review portion, the HPO field is listed as  "_Not selected..._"
6. In the Status portion, the HPO term is back, and is retained in the gene list.

The HPO terms that were already selected should remain selected like they do for the other resources.

Also, when I click Edit, there is a message at the bottom of the modal that reads "The disabled items indicate that the search term is already reviewed and searched. You can delete it from the "Terms" panel." 

I'm not sure what this means, I don't see that icon anywhere. What is this telling me?

**Comment by adityaekawade** [comment]
The message is shown when the modal is opened to edit. 
<img width="881" alt="Screen Shot 2020-04-12 at 10 51 50 AM" src="https://user-images.githubusercontent.com/16284713/79076087-28443800-7cac-11ea-84b3-77119497ea08.png">

In this example, Charcot marie tooth disease was reviewed and is disabled in the edit mode as the gene list is already built with it. You can delete this term from the "Terms" panel when this modal is closed. (The delete icon is shown on hover)   
<img width="260" alt="Screen Shot 2020-04-12 at 11 02 02 AM" src="https://user-images.githubusercontent.com/16284713/79076261-91787b00-7cad-11ea-9f45-7d34f4a98157.png">

**Comment by AlistairNWard** [comment]
Ok, I see. That wasn't that clear to me. I didn't try and deselect Charcot Marie Tooth, and didn't notice that the check box is gray rather than blue, so I didn't realise it was disabled.

@tonydisera @mvelinder Is this confusing to either of you? It seems logical to me that if I'm in Edit mode, I should be able to remove as well as add terms. I'm assuming there is a reason that this is disabled as opposed to being deselectable - what is the reason?

**Comment by adityaekawade** [comment]
I don't remember exactly, but I was noticing some problems related to the state if the term was allowed to be removed from the edit modal. Hence, I had disabled the selected terms in edit mode.
 
I agree it makes sense to add or remove terms in edit mode. I will go ahead and create a separate issue its fix.

**Comment by AlistairNWard** [comment]
Thanks @adityaekawade

**Comment by mvelinder** [comment]
I'd agree, in Edit mode you should be able to change the terms selected. And all previously selected terms should show up for (de)selection. Let's try to include this for the new release @adityaekawade
