### ISSUE TITLE
Clin description

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/clin.iobio#174]
Clin needs a description in the Mosaic launch menu. We can add this on Frameshift Mosaic, but should we manually update Utah Mosaic for clin release without requiring pushing a new version of Mosaic?

Feel free to edit the description below

"An iobio app to define and review clinical phenotypes and variant, generate prioritized gene lists, and create a report summarizing all findings"

**Comment by tonydisera** [comment]
"An iobio app for a diagnostic variant analysis workflow, including clinical phenotype selection, phenotype-to-gene associations, variant prioritization and collaborative variant review and summarized findings"

**Comment by anderspitman** [comment]
@chmille4 @AlistairNWard where does this need to be changed?

**Comment by adityaekawade** [comment]
I think its the apps launch menu: 

<img width="827" alt="Screen Shot 2020-04-14 at 1 27 56 PM" src="https://user-images.githubusercontent.com/16284713/79271024-fd94e380-7e53-11ea-83b0-f4a60efeeec3.png">

**Comment by anderspitman** [comment]
Right, I meant is there a way for me to make the change in our database or do we need changes in Mosaic?

**Comment by AlistairNWard** [comment]
It will also need changing in Mosaic, and it's just an sql command (I obviously don't know said command). We may want to make a minor Mosaic release anyway, so maybe we just wait on Frameshift to fix this.

**Comment by anderspitman** [comment]
kk

**Comment by adityaekawade** [comment]
This is added in Mosaic. I am closing this issue.
