### ISSUE TITLE
show HPO terms in gene associations

### ISSUE THREAD

**Issue by adityaekawade** [iobio/clin.iobio#182]

**Comment by adityaekawade** [comment]
Hi, I am adding the feature to show the associated HPO entries in the Gene-associations card and in the left panel flagged variant card which was missing. I am currently showing only the HPO id for the HPO term as space is limited to show both. I also made some tweaks to the chips and I wanted some feedback on it before I do a pull request. Please see the attached screenshot. 
<img width="1680" alt="Screen Shot 2020-04-17 at 10 46 15 AM" src="https://user-images.githubusercontent.com/16284713/79598563-0e826680-8099-11ea-9ffb-c8a4b68c99e3.png">

@tonydisera @mvelinder @AlistairNWard

**Comment by AlistairNWard** [comment]
I would suggest we have a "Show more..." or something like that after the gene associations. We need to make sure we aren't misleading users in any way. Looking at the screenshot, I would assume that the gene is only associated with one HPO term. If that isn't the case, we need that to be clear. If space is the issue, maybe we show badges that show the gene rank for GTR/Phenolyzer and the associated terms are in a show more.

**Comment by adityaekawade** [comment]
<img width="1207" alt="Screen Shot 2020-04-20 at 12 46 37 PM" src="https://user-images.githubusercontent.com/16284713/79793199-02024600-8305-11ea-9ed7-b398d29778b9.png">

**Comment by adityaekawade** [comment]
I made the following changes as per our discussion yesterday: 

- Displaying Hpo phenotype instead of Hpo id. 
- Limiting the number of terms to be shown in the card 

<img width="627" alt="Screen Shot 2020-04-21 at 3 29 41 PM" src="https://user-images.githubusercontent.com/16284713/79921208-9f817680-83e6-11ea-963f-203e4142eb26.png">

- Added a "show more" button which open a dialog and shows all the gene associations (the terms are organized in a tabular layout like in step 2). 
"Show more" button is only shown when the number of associations is more than 3. 


<img width="1664" alt="Screen Shot 2020-04-21 at 2 18 27 PM" src="https://user-images.githubusercontent.com/16284713/79921254-b3c57380-83e6-11ea-9c7f-37d0a59df0b2.png">

Added a tooltip on the rank-chip in the left panel to briefly explain the ranks. 
<img width="326" alt="Screen Shot 2020-04-21 at 2 18 55 PM" src="https://user-images.githubusercontent.com/16284713/79921640-7b726500-83e7-11ea-8356-e5b2e557d039.png">

**Comment by adityaekawade** [comment]
@tonydisera I am adding you as a reviewer for this issue. There are  Pull requests associated with this issue both in gene.iobio repo and clin.iobio repo.

https://github.com/iobio/clin.iobio/pull/190

https://github.com/iobio/gene.iobio.vue/pull/474

It required some additions to the hpo data in `genesReport`, so  PR in clin.iobio repo does that. The PR in gene.iobio repo handles it and the necessary UI updates . 

Steps to test: 

- Clone the branch `hpo-associated-genes` from gene.iobio 


- Clone the branch `hpo-terms-gene-association` from clin.iobio repo. 
- Do `npm install` to update the necessary component 
- `npm start`, server should be running on the port 4030.

Let me know if you have any questions or if anything needs to be changed.

**Comment by mvelinder** [comment]
Let me know when I can test on stage.clin

**Comment by adityaekawade** [comment]
@mvelinder ready for testing on stage.clin

**Comment by mvelinder** [comment]
@adityaekawade @WilliamRichards2017 from my testing this still is an issue here https://github.com/iobio/gene.iobio.vue/issues/489

We can close this, but need to resolve the issue above that @WilliamRichards2017 is working on

**Comment by WilliamRichards2017** [comment]
@mvelinder https://github.com/iobio/gene.iobio.vue/issues/489 is attached to a pull request with you as the assigned reviewer.  Let me know if that PR fixes the issue and I can go ahead and merge it!

**Comment by mvelinder** [comment]
Done
