### ISSUE TITLE
Create a service to keep HPO data updated

### ISSUE THREAD

**Issue by adityaekawade** [iobio/clin.iobio#184]

**Comment by adityaekawade** [comment]
I have created a new service to get the updated data for HPO by running a simple one-line script. It fetches the data from the source, does processing, and generates the required files all in under 4 minutes. 
Repo: https://github.com/adityaekawade/hpo_to_genes
@mvelinder

**Comment by mvelinder** [comment]
Cool! Do you need me to test it? If so, how? If not, let's just go ahead and get it incorporated into clin

**Comment by adityaekawade** [comment]
Yup, it's incorporated in stage.clin. Related issue #201 (waiting for final review). 
Also if you want to test the above service, you can clone the repo and run the script `index.sh and there should be 4 files created in the `output_files` folder.
