### ISSUE TITLE
Show gene info and chromosome viz in the gene list

### ISSUE THREAD

**Issue by adityaekawade** [iobio/clin.iobio#186]
This feature shows more information about the gene along with its chromosome visualization. 
<img width="799" alt="Screen Shot 2020-04-19 at 12 36 47 AM" src="https://user-images.githubusercontent.com/16284713/79682303-ef3d2380-81d5-11ea-968e-fe12ccdb103e.png">

**Comment by adityaekawade** [comment]
From the genes table by clicking the following icon or the gene name
<img width="1610" alt="Screen Shot 2020-04-21 at 9 01 44 AM" src="https://user-images.githubusercontent.com/16284713/79887011-e18ec600-83ae-11ea-946b-3d40ed50c212.png">

**Comment by mvelinder** [comment]
Looks good!
