### ISSUE TITLE
For GTR genes, explain what the shield means in a hover over, or just remove them entirely

### ISSUE THREAD

**Issue by mvelinder** [iobio/clin.iobio#189]
![image](https://user-images.githubusercontent.com/22081541/79890579-ef4b4800-83bc-11ea-845c-fc7feca8822b.png)

Currently it's just an icon with no meaning or explanation and likely confusing to people

**Comment by adityaekawade** [comment]
@mvelinder I am adding the "review complete" tag here since you added it on the Pull Request for this issue.
