### ISSUE TITLE
Add PHAROS gene:drug target information to report page

### ISSUE THREAD

**Issue by mvelinder** [iobio/clin.iobio#197]
https://pharos.ncats.nih.gov/api

**Comment by adityaekawade** [comment]
I looked into the API for PHAROS and also compared it with the DGIdb API. Both seem to show some common drugs for a gene name, but there are some differences as well. 

Consider the case for the gene: **KCNH2**

Pharos: https://pharos.nih.gov/idg/api/v1/ligands/search?facet=IDG%20Target/KCNH2
The drugs list can be found in the properties "IDG DRUGS" and "content". It also shows the "LIGAND" information, which I think is the chemical structure in organic chemistry. 

DGIdb: http://dgidb.org/api/v2/interactions.json?genes=KCNH2
The DGIdb API is simple to use, and the output seems to be much better organized. It displays the drug name, drugChemblId, sources, and the results can be filtered to show only the FDA approved drugs. 
 
We need to consider what information needs to be shown in the report and how much information will be helpful. For example "KCNH2" is marked as significant. Do we want to list the FDA approved drugs for it or we want to list the ligands as well? We can have a discussion and add this feature to the reports page.

**Comment by AlistairNWard** [comment]
Not really read this, but there is also openTargets as another resource that has drug information that may also be worth looking at.

**Comment by mvelinder** [comment]
Thanks for looking into that @adityaekawade , we can use DGIdb for simplicity. We could consider a badge for the drugs that are FDA approved or something like that.

**Comment by adityaekawade** [comment]
Yeah, that sounds good. Using DGIdb and a badge for FDA approved drugs. 

I also explored the OpenTarget API. Its data is structured based on the associations (Gene -> Ensembl Gene ID -> Disease -> Drug). 

Consider the  API request for the gene  **KCNH2**

https://platform-api.opentargets.io/v3/platform/public/evidence/filter?target=ENSG00000055118&datasource=chembl&size=15&datatype=known_drug

And this is one of the properties from the response. 
<img width="625" alt="Screen Shot 2020-05-05 at 4 11 06 PM" src="https://user-images.githubusercontent.com/16284713/81125182-50f6d080-8eec-11ea-8325-1e9e0c599ba4.png">
So for this gene (KCNH2), Atrial fibrillation is one of the associated diseases, and AMIODARONE is the drug that is associated with Atrial fibrillation. 

You can get similar information from their web view: https://www.targetvalidation.org/target/ENSG00000055118

**Comment by mvelinder** [comment]
Sounds good, the most straightforward disease/phenotype > gene > drug association we can present is best. Thanks for looking into additional sources. I didn't know about targetvalidation.org

**Comment by adityaekawade** [comment]
I have created a Pull Request #208 to show drug information for a gene in the findings page. I have used the Open Targets resource for this information.

You can try it on: http://dev.clin.iobio.io/

Screenshots of this feature: 
<img width="1664" alt="Screen Shot 2020-05-14 at 3 08 58 PM" src="https://user-images.githubusercontent.com/16284713/81991870-14675b00-95f7-11ea-8354-1e69575ec092.png">
<img width="1574" alt="Screen Shot 2020-05-14 at 5 54 49 PM" src="https://user-images.githubusercontent.com/16284713/82000245-9150ff80-960c-11ea-95dd-c5ee75665293.png">

**Comment by mvelinder** [comment]
I tested on dev.clin. This is looking really cool @adityaekawade !

**Comment by adityaekawade** [comment]
Thanks Matt! 
Tony also has reviewed and approved its PR, so it is live on stage.clin now!
