### ISSUE TITLE
Fix HPO gene association in Findings page

### ISSUE THREAD

**Issue by adityaekawade** [iobio/clin.iobio#203]

**Comment by adityaekawade** [comment]
<img width="246" alt="Screen Shot 2020-05-05 at 4 43 52 PM" src="https://user-images.githubusercontent.com/16284713/81126325-cfa13d00-8eef-11ea-89fc-d562922bb098.png">
Similar issue #182

**Comment by AlistairNWard** [comment]
Not sure what the problem was to confirm the fix

**Comment by adityaekawade** [comment]
I think it was a formatting or styling issue. If you look at the screenshot attached in the comments here, the red badge only showed "#" for the HPO association in the findings page. This was fixed to have consistent formatting across "review-variants" and "findings" page.
