### ISSUE TITLE
Add functionality for a config file to avoid copy/paste into every field during data input

### ISSUE THREAD

**Issue by mvelinder** [iobio/clin.iobio#211]
Maybe a tsv format similar to a ped file with more fields where the additional columns specify the vcf and bam urls for that sample?

**Comment by adityaekawade** [comment]
I have added functionality to save the entered information as a config file and use it to avoid copy/ paste the same information when launching clin.iobio next time. You can test it on http://dev.clin.iobio.io/

@mvelinder , a tsv file option is also a  good idea. We can provide a template that can be used to enter the information. 

This will require validating the imported file. I have created another issue for that #222
