### ISSUE TITLE
Automatically toggle/assign affected status based on the pedigree

### ISSUE THREAD

**Issue by mvelinder** [iobio/clin.iobio#215]
Pull affected status directly from the ped file and toggle Affected appropriately

![image](https://user-images.githubusercontent.com/22081541/83558271-01e29200-a4d0-11ea-885e-56226e96a716.png)

**Comment by adityaekawade** [comment]
This feature will require some discussion. I have set up the ped file input as a required step but does every user with access to VCF or BAM files has PED files ready to be used? Or can the PED input be an optional field? @will had mentioned that the PED input is currently the last step, but should it be moved ahead of files input? 

Two options we can try: 
1. PED input is required and this step is before the files entry. It then assigns the affected status based on the pedigree information and the affected toggle option is hidden from the user. 
2. PED input is optional. But if the user skips this step, the toggle option is shown to the user.

**Comment by will** [comment]
“ @will had mentioned that the PED input is currently the last step”

Do you mean @pedro ? He sometimes goes by just ped, but I don’t remember getting input from him in a while. I mean we’ve been talking about a discord bot, but I don’t think I would have ever brought that up here. I haven’t even seen this project before. 

What’s going on?

**Comment by adityaekawade** [comment]
> “ @will had mentioned that the PED input is currently the last step” Do you mean @pedro ? He sometimes goes by just ped, but I don’t remember getting input from him in a while. I mean we’ve been talking about a discord bot, but I don’t think I would have ever brought that up here. I haven’t even seen this project before. What’s going on?
> […](#)
> On Jun 5, 2020, at 18:22, Aditya Ekawade ***@***.***> wrote: @will had mentioned that the PED input is currently the last step

Sorry, looks like wrong @will got tagged.

**Comment by mvelinder** [comment]
Agreed, PED on the last step doesn't make sense. I'd say:

1) Load config file (from previous analysis if possible)
2) Load PED file, automatically pull relatedness and affected status from it
3) Load VCF/BAM files (making sure BAM/VCF sample IDs match the PED)

Throw warnings when the above don't match. (BAM/VCF/PED sample IDs don't match, etc)

Seem reasonable?

**Comment by adityaekawade** [comment]
Make sure to validate input data. Issue #227

**Comment by adityaekawade** [comment]
I have rearranged the input workflow steps as follows: 
Case description -> Pedigree input -> Files -> Gene Set

The sex of the individual and the affected status is automatically set from the imported ped file. The toggle switch is still there which can be used to override the affected status setting as we had discussed yesterday.
 
Test: http://dev.clin.iobio.io/

**Comment by AlistairNWard** [comment]
Once I add URLs and samples to the files and click next, nothing happens.

**Comment by adityaekawade** [comment]
Can you share the URLs? I will check what's going wrong.

**Comment by AlistairNWard** [comment]
I was using the ones that Matt shared on one of the other issues

**Comment by adityaekawade** [comment]
I will have fix for it tomorrow.

**Comment by adityaekawade** [comment]
@AlistairNWard You should be able to test it on http://dev.clin.iobio.io/. 
URLs for your reference: 
https://s3.amazonaws.com/iobio/samples/vcf/platinum-exome.vcf.gz
https://s3.amazonaws.com/iobio/samples/bam/NA12878.exome.bam
https://s3.amazonaws.com/iobio/samples/bam/NA12892.exome.bam
https://s3.amazonaws.com/iobio/samples/bam/NA12891.exome.bam
https://s3.amazonaws.com/ped.test.files/platinum.ped


Also, I have been experimenting by using the standard BED file as default. So you should be able to see the coverage charts. Let me know if this works. And since this is in dev, do let me know if you see any other bugs or if something does not work. Thanks 
<img width="1459" alt="Screen Shot 2020-06-11 at 8 41 24 AM" src="https://user-images.githubusercontent.com/16284713/84415722-0857c480-abc8-11ea-96d7-5655950c0145.png">

**Comment by AlistairNWard** [comment]
Ok, I get through all the steps now.

I saw a problem with the pedigree and your screenshot shows the same thing. The proband (top) is the marked as the unaffected sib and the mother is the proband.

How do you determine whether to use the bed (for exomes), or not?

**Comment by adityaekawade** [comment]
Right now, I am using the standard bed for all the requests. But this is what I am planning to do: 
Provide the user with the following options when importing VCF and BAM files: 

- Add a custom bed file
- Standard GRCh37 bed
- No bed file 

I don't think I can determine if the entered URL is for exomes unless the URL includes the word "exome" in it. 

Oh. I had not noticed the pedigree problem. Looks like it mapped data in the incorrect order.

**Comment by AlistairNWard** [comment]
Ok, that makes sense. Maybe when providing the choice of entering a bed file, it should be presented as the user choosing if this is exome or whole genome data - not everyone will necessarily know what a bed file is, and so won't know how to answer. If the user selects exome, then they choose to provide a bed or use a default. We should make sure we have a default for GRCh38 as well. I'll take a look to see if a consensus bed exists for this.

**Comment by adityaekawade** [comment]
Yeah, that sounds good. 
Is the bed file stored and accessed from a URL like VCF or BAM? I can set it up in a way that the user can either upload the bed file or enter the URL. But if we are going to be saving the state of input data in a config file (#211 ), we might have to think of a data storage solution and put a reference to it in the config as the bed file can be large in size.  Or the URL options seem the easiest for now?

**Comment by adityaekawade** [comment]
The standard BED file is about 4.6 MB, which is not bad to be saved.
