### ISSUE TITLE
Change Upload data to Load data

### ISSUE THREAD

**Issue by mvelinder** [iobio/clin.iobio#219]
![image](https://user-images.githubusercontent.com/22081541/83894513-9fc3a000-a70e-11ea-8fb1-aba4d9328fbd.png)

To more closely match the language on gene.iobio

**Comment by adityaekawade** [comment]
Fixed this on http://dev.clin.iobio.io/

**Comment by mvelinder** [comment]
Sorry, can we actually do "Load your data" instead of "Load data"?

Thanks!

**Comment by adityaekawade** [comment]
Sure. Also, it is "Run with demo data" on gene.iobio with all uppercase letters. I will match this on clin.iobio

**Comment by mvelinder** [comment]
Sure, let's just make them the same as gene.iobio.

RUN WITH DEMO DATA

LOAD YOUR DATA

**Comment by adityaekawade** [comment]
DONE!
