### ISSUE TITLE
Allow for ped file URL input too

### ISSUE THREAD

**Issue by mvelinder** [iobio/clin.iobio#220]

**Comment by adityaekawade** [comment]
Do you have an example URL for PED file?

**Comment by mvelinder** [comment]
Here's the platinum data ped file as a URL 

https://raw.githubusercontent.com/mvelinder/ped_draw/master/examples/platinum.ped

**Comment by adityaekawade** [comment]
Test: http://dev.clin.iobio.io/

Also, I have uploaded ped file on s3 bucket for testing: 
https://s3.amazonaws.com/ped.test.files/platinum.ped

**Comment by mvelinder** [comment]
@adityaekawade I can't click Load when using a ped file URL

![image](https://user-images.githubusercontent.com/22081541/84155534-aa8b7700-aa25-11ea-940b-f23206a8a43e.png)

**Comment by adityaekawade** [comment]
It seems to be working. I tried in both chrome and firefox. It might take a few seconds to enable the button while the data is fetched, but should not take long. 

![ped-url-demo-](https://user-images.githubusercontent.com/16284713/84159503-f9cfa880-aa21-11ea-9add-f1bff3163719.gif)
