### ISSUE TITLE
Make sure .ped file extension is supported not just .txt 

### ISSUE THREAD

**Issue by mvelinder** [iobio/clin.iobio#221]

**Comment by WilliamRichards2017** [comment]
.ped extensions are supported, I renamed the testPed.ped file to testPed.txt, as you are unable to upload files to github with the .ped extension.  This can be verified by renaming the test ped file to use the .ped extension

**Comment by mvelinder** [comment]
Awesome, thanks. Just double checking. I wasn't able to test since my dev.clin wasn't loading. I'll cloe this
