### ISSUE TITLE
Legend is blocking the view in "review-variants" and cannot be dismissed

### ISSUE THREAD

**Issue by adityaekawade** [iobio/clin.iobio#230]

**Comment by adityaekawade** [comment]
<img width="1368" alt="Screen Shot 2020-06-11 at 9 28 35 AM" src="https://user-images.githubusercontent.com/16284713/84414109-5b307c80-abc6-11ea-87f7-6a6c748dd383.png">

**Comment by WilliamRichards2017** [comment]
I temporarily disabled the  gene legend when launched from clin, until we figure out how we want to display the legend.  This issue is fixed with the gene PR https://github.com/iobio/gene.iobio.vue/pull/533
