### ISSUE TITLE
Wordings and documentation

### ISSUE THREAD

**Issue by adityaekawade** [iobio/clin.iobio#244]
I just have created a google doc and added some screenshots that will require help text or documentation for clarity to the user. Feel free to add or edit. 
Link: https://docs.google.com/document/d/1jwX0-guC1sonqx14F9aPE-XgiYY6MhgaywzmyhoO9-E/edit?usp=sharing

**Comment by mvelinder** [comment]
Have these changed been made in the app given the comments @AlistairNWard and I made in the Google doc? If so, we can close this issue

**Comment by adityaekawade** [comment]
I have addressed the comments from the google doc. I will close this issue.
