### ISSUE TITLE
Bad ped fails on bam/vcf file input

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/clin.iobio#248]
I started a clin session with my own data. I put in a malformed ped (comma, rather than tab separated), and I passed on to the next step. I put in the bam and vcf files, then click Next. The little load icon spins for a bit, then stops, but I can't move past this page, but no errors are presented. The problem is that the ped is bad, but there is no indication to the user.

We should be checking the ped file when we input and fail at that step if there is a problem.

**Comment by adityaekawade** [comment]
Though the ped file is recommended to be tab-separated, I have added checks so it can comma-separated ped files and should work. 
However, if the VCF data does not match with the ped input such as sample id, it will show errors: 
<img width="873" alt="Screen Shot 2020-07-20 at 3 19 15 PM" src="https://user-images.githubusercontent.com/16284713/87992309-d6762f80-ca9c-11ea-8b02-c07ed9d60ad1.png">

Also, it will do a check if see if the required number of columns are there in the ped file. 
<img width="881" alt="Screen Shot 2020-07-20 at 3 24 06 PM" src="https://user-images.githubusercontent.com/16284713/87992506-4a183c80-ca9d-11ea-9e78-a0ee61774371.png">

**Comment by AlistairNWard** [comment]
This is successful at accepting a comma separated bed and catching errant sample names in the ped. However, I put in the incorrect sample id for parents and clin loaded, but the pedigree charts were missing.

**Comment by adityaekawade** [comment]
@AlistairNWard Just to confirm the behaviour, you entered an incorrect sample id in the "Paternal_ID" or "Maternal_ID" column right and not an incorrect sample id? 
For example, the Fathers' id: NA12891, Mother's id: NA12891, proband's id: NA12878. 
So you entered Paternal_ID as NA12893 instead of NA12891 for the proband?

**Comment by adityaekawade** [comment]
It will show an error when incorrect sample id's are entered for parents and will not proceed from the Pedigree upload step. You can try it on stage.clin.

**Comment by AlistairNWard** [comment]
Exactly, we need to be sure that not only proband ids are checked and ok, but that parental ids are also valid. E.g. any id appearing in a paternal or maternal field must also be a sample in the ped. Paternal and maternal ids can't be the same. And the maternal (paternal) id should be pointing to a female (male) sample etc.

**Comment by adityaekawade** [comment]
Okay. I have missed the last condition check. I will add that and tag for review once it's ready.

**Comment by adityaekawade** [comment]
I have added checks for the above conditions. Please give it a test at stage.clin and let me know if it's missing anything else.

**Comment by AlistairNWard** [comment]
All these cases are correctly caught. But I think that the wording for some of the errors might not be super informative to a user, so here are some alternative suggestions. I am assuming that you know the sample ids of the proband (when the parents have the same id), or the parents when an error is made. If so, if we provide this to the user, they will be able to find the error quickly in a multi sample ped file, rather than just knowing that somewhere there is a bad id.

@mvelinder @tonydisera Thoughts on the error messages?

**Paternal id = Maternal id**
Current message is "Duplicate sample id's entered for parents. Please correct and try again."
Replace with:
"Maternal and paternal ids are identical for sample XXX. Please ensure these ids correctly represent the samples mother and father."

**Invalid maternal / paternal id**
Current message is "Incorrect sample id's entered for parents. Please correct and try again"
Replace with:
"Sample XXX has maternal id YYY, but this sample is not present in the ped. Please ensure that the maternal id is entered correctly, and if so, that this sample has their own row in the ped file"

Change the above to paternal when the error is with the paternal id.

**Incorrect maternal (paternal) sex**
Current message is "Sample id's are incorrectly mapped for parents. Please correct and try again."
Replace with:
"Sample XXX is listed as the father (mother) of sample YYY, but is listed as being female. Please ensure that the paternal (maternal) id for sample YYY correct, and if so, ensure that the sex of sample XXX is listed as male (female)"

Use male/female, maternal/paternal as necessary

**Comment by tonydisera** [comment]
Yes, I agree with your suggested rewordings.

 

T

**Comment by adityaekawade** [comment]
It should catch and show all the errors from ped file. 
<img width="880" alt="Screen Shot 2020-08-20 at 8 45 55 AM" src="https://user-images.githubusercontent.com/16284713/90796425-29255000-e2c4-11ea-8739-fb676a0457ec.png">
