### ISSUE TITLE
Allow variant set input (not Mosaic)

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/clin.iobio#250]
Instead of requiring a list of genes to launch clin, allow the user to add their own variants (via vcf?)

**Comment by adityaekawade** [comment]
The users can now import custom variants such as exported from gene.iobio in csv format. 
<img width="889" alt="Screen Shot 2020-07-22 at 11 25 42 AM" src="https://user-images.githubusercontent.com/16284713/88213850-24f70b80-cc0e-11ea-948f-5db1666a79eb.png">

**Comment by AlistairNWard** [comment]
This is working and looks good to me
