### ISSUE TITLE
Improve explanation

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/clin.iobio#251]
We should include clear descriptions of what clin is taking as input and why. There could be confusion between the gene list used to get variants, and the gene list generated by phenotype search. The difference and reasons for these should be clear.

**Comment by mvelinder** [comment]
@AlistairNWard and I can provide this very quickly when we're closer to a stable release and once we've dealt with other issues.

**Comment by mvelinder** [comment]
![image](https://user-images.githubusercontent.com/22081541/90141846-e3530f80-dd38-11ea-980e-b80945b11d23.png)

Change this text and the text in the progress bar up top to be: 
Genes/variants

And add this short description below the (now) Gene/variants subheading and above the Enter gene dialog:
Users can enter a list of genes or variants into clin.iobio. These are the genes and/or variants that will be reviewed in the clinical workflow steps of the app.

**Comment by mvelinder** [comment]
Do you think we need descriptions about the genes and variants elsewhere @AlistairNWard ?

**Comment by AlistairNWard** [comment]
Good question. I think it would be a good idea to go through the whole process of getting data into clin (using all methods - demo, files, urls, config files), and then going through each page of the app in a standard analysis workflow and see if we identify areas that need explanation. I'll try and do that today.

**Comment by adityaekawade** [comment]
Yeah, we can add a tooltip with info icon to show more information such as the file specifications etc.. 
 
<img width="868" alt="Screen Shot 2020-08-13 at 8 15 05 AM" src="https://user-images.githubusercontent.com/16284713/90152947-3f1f9780-dd3d-11ea-9f68-350d339896c0.png">
