### ISSUE TITLE
Review top N genes

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/clin.iobio#252]
We could look at the idea of an additional workflow step to review the variants in the top N genes provided by the phenotype step. This would be genes that are strongly linked to the phenotype, but weren't identified by the supplied variant/gene set.

**Comment by mvelinder** [comment]
You beat me to it

**Comment by AlistairNWard** [comment]
I'll have forgotten everything that was said in about 3 minutes, so had to get them down quickly!

**Comment by mvelinder** [comment]
If this is going to hold up the public release of clin, I'd say we push it to the next release

**Comment by adityaekawade** [comment]
Yeah, let's do this in the next release.

**Comment by adityaekawade** [comment]
Should we limit the number of selected genes to be reviewed? For example, the user can select up to 25 or 50 genes from the phenotype step to be reviewed and add it to the supplied gene set.

**Comment by AlistairNWard** [comment]
Yes. I put that we should be able to review the top N, so we just need a good, and maybe dynamic value for N. We can default to 25, but allow the user to increase the limit, but cap the number to be no more than 100?

**Comment by adityaekawade** [comment]
Yeah, that sounds good. 100 max should be a good number. 
I am also adding "add to gene set" checkbox, so genes can also be reviewed and selected individually.
<img width="1114" alt="Screen Shot 2020-09-15 at 12 44 54 PM" src="https://user-images.githubusercontent.com/16284713/93257830-4da10a80-f752-11ea-84a9-54cb478fc9b2.png">

**Comment by AlistairNWard** [comment]
These are my recollections of the steps needed in clin:
1. By default, select the top 20 genes from the gene list to pass to the variant review step
2. Allow the user to add or remove genes from the list to pass on, including the ability to add e.g. the top 30
3. Gene.iobio updates will identify the sources of genes in the review variants step
4. In the findings page, include the source in the final table

**Comment by adityaekawade** [comment]
You can test this functionality on http://dev.clin.iobio.io/ and try with demo data. 

1. 20 genes will be selected by default in the "Select phenotypes" step. These selected genes will be passed to the "review variants" step. You can change selection but the limit is 50. Also, there is a new visualization that will show the percentage of the number of genes selected from the total number of genes available. 
![Screen Shot 2020-09-30 at 1 56 21 PM](https://user-images.githubusercontent.com/16284713/94740944-466c2600-0328-11eb-80a5-220f4a551491.png)

2. The "review variants" will be updated: 
![Screen Shot 2020-09-30 at 1 58 15 PM](https://user-images.githubusercontent.com/16284713/94741039-66034e80-0328-11eb-98fd-578674dee524.png)
The "genes" tab will have the source indicated next to each gene. Legend is at the bottom. (_I noticed I have made a typo here.. It should be source instead of sources_)


![Screen Shot 2020-09-30 at 1 57 54 PM](https://user-images.githubusercontent.com/16284713/94741296-c6928b80-0328-11eb-9ef4-996b480c9080.png)
Similarly, the variants tab has the source indicated and the legend is at the bottom. 
The variant inspect card shows the source for the variant. 

3. The variant card in the findings page also indicates the source. 
![Screen Shot 2020-09-30 at 1 58 44 PM](https://user-images.githubusercontent.com/16284713/94741525-17a27f80-0329-11eb-8c38-ede4e5a99fae.png)

Please try it out and let me know if any changes are required. If everything looks good, then it is good for a new release! Also, we can show it in the clinical iobio meeting tomorrow if we review clin.iobio. 
@AlistairNWard @mvelinder

**Comment by AlistairNWard** [comment]
I agree with @mvelinder's concern about showing the percentage of genes. I don't think that's a necessary visual and might be more problematic than helpful.

Trying to work through this as a naive user, I'm pretty sure they won't find the legend at the bottom of the left menu, so the what the source is might be confusing. My guess is that once you're looking at the set of variants, most users won't particularly care what the variant source is. More advanced users would probably find it more useful. With that in mind, what do you think about removing the legend:

![Asset 1](https://user-images.githubusercontent.com/523111/94946982-ed78cb00-04aa-11eb-94e0-5ab74d774621.png)

In the variant list (and could be mirrored in the gene list), I put the source in a red circle which looks consistent with the rest of the look to me. Instead of a legend, I would suggest we just have a tooltip over the circles that describes the source. I also got rid of the text in the variant card. Again, if most users aren't too interested in the source, there probably isn't need to take up all the space the text requires. Also, if the variant is in a gene identified in multiple sources, there could be a lot of text, so just a more subtle indication of the sources with tooltip should be enough.

Thoughts?

**Comment by adityaekawade** [comment]
Okay, I will remove the visual showing the percentage of genes selected. 
I agree the legend on the left menu is way at the bottom, and even I felt like I was closing many expansion panels just to get a screenshot to show it. 
The tooltip idea is good, but are there too many small circles on the page now? Badges on the nav section, source indicators, one showing "exons with insufficient coverage".. just a thought, but we can go ahead with this idea.

**Comment by adityaekawade** [comment]
Ready for the test with new badges and removed the genes % viz.
http://dev.clin.iobio.io/
@AlistairNWard  @mvelinder

**Comment by AlistairNWard** [comment]
Couple of comments:
1. The number of selected genes is underlined with a blue dashed line. This should probably just be a regular text box
2. Can we have an info badge with tooltip on the genes selected. A user won't know what these genes are selected for, so a quick explanation of what you are selecting genes for would be beneficial
3. The contrast between the gray check mark and the gray plus symbol for adding genes is quite subtle. Can we make the distinction between which genes are selected and which can be selected clearer.

I think everything else looks good @adityaekawade . This is a big improvement. I think we could do with improving the text describing the sources. I can take a stab later today at text for:
1. Describing the sources
2. Explaining the selected genes

Anyone else is welcome to take a stab as well...

**Comment by adityaekawade** [comment]
1. I had kept it underlined so it can draw attention and that value can be changed. But I am okay to keep just a regular text box. 
2. So each selected gene in the gene list table will have an info badge next to it right? The selected checkbox has a tooltip that currently says "**GENE** is added to the gene set". Should we add the explanation here instead? 
3. I will use the following icon to show unselected genes: 
![Screen Shot 2020-10-05 at 11 48 25 AM](https://user-images.githubusercontent.com/16284713/95119393-bdc30080-0700-11eb-921d-79600996467c.png)


I will make the above changes. Comment here or message once you are ready with the text for the explanation, I will add it and we will be ready for the release.

**Comment by AlistairNWard** [comment]
> 2. So each selected gene in the gene list table will have an info badge next to it right? The selected checkbox has a tooltip that currently says "GENE is added to the gene set". Should we add the explanation here instead?

No, I meant an info box next to where you select the number of genes. They have selected 20 genes, but don't necessarily know what they have selected those genes for

**Comment by adityaekawade** [comment]
Oh right! I had added an icon there with tooltip a few versions back for the same reason. I will add it back.

**Comment by AlistairNWard** [comment]
Sorry @adityaekawade for not getting those text descriptions written. I just reran clin and there is a bit of text:

<img width="1626" alt="Screen Shot 2020-10-06 at 8 15 25 PM" src="https://user-images.githubusercontent.com/523111/95273343-d4f11380-0810-11eb-930f-5d754ebf3433.png">

This just disappears after a short time though and I'd missed it before. I think it might make sense to get rid of this message and replace it with a tooltip on the Genes table title (to explain the list), and the N genes selected text. I would suggest the following:

**Genes (table title)**
The entered clinical note is used to generate the following list of genes that may be associated with the patient's phenotypes and/or disorder. These disease:gene associations are used in the _Review Variants_ step.

**genes selected**
All variants in the genes selected here will be analyzed in the _Review Variants_ step. You can manually add or remove genes from the list, or choose the top N genes (20 by default) to analyse.

**Sources**
Is it possible to have a slightly different description of the source when on the Genes tab? If so, we could use the following for the Variants tab and on the variant detail:

1. Variant is a member of an imported set of potentially interesting variants
2. Variant is in a gene associated with the patient's clinical note

and the following on the genes tab:

1. Genes contains an imported potentially interesting variant
2. Gene is associated with the patient's clinical note
