### ISSUE TITLE
Clipping of Total: text

### ISSUE THREAD

**Issue by mvelinder** [iobio/clin.iobio#262]
![image](https://user-images.githubusercontent.com/22081541/88218013-ab1a4e80-cc1c-11ea-9b16-0a625f12c39f.png)

The top of Total: is getting clipped by something?

**Comment by adityaekawade** [comment]
Fixed.
<img width="397" alt="Screen Shot 2020-07-24 at 10 37 11 AM" src="https://user-images.githubusercontent.com/16284713/88419233-afb84180-cd99-11ea-8a4f-9ba5c896f746.png">

Test: http://dev.clin.iobio.io/
