### ISSUE TITLE
Case summary not going to full width

### ISSUE THREAD

**Issue by mvelinder** [iobio/clin.iobio#263]
![image](https://user-images.githubusercontent.com/22081541/88218194-ed439000-cc1c-11ea-866e-87a6dfb470c6.png)

Seems like the case summary should be going further right to the full width?

**Comment by adityaekawade** [comment]
<img width="1680" alt="Screen Shot 2020-07-24 at 10 36 00 AM" src="https://user-images.githubusercontent.com/16284713/88419167-8697b100-cd99-11ea-8312-687d2f4440a1.png">


Test: http://dev.clin.iobio.io/
