### ISSUE TITLE
Interpreting variant dialogue pops up when adding a significance

### ISSUE THREAD

**Issue by mvelinder** [iobio/clin.iobio#265]
Not sure what this dialogue is

![image](https://user-images.githubusercontent.com/22081541/88219280-99d24180-cc1e-11ea-9cfd-3a80e6ec316a.png)

It took about 10 seconds to do whatever it was doing then went away and the significance was added. Do we need to have it do this?

**Comment by adityaekawade** [comment]
This is added as a progress indicator. 

Long story: Gene.iobio was making additional requests for all the genes while setting and saving analysis in clin.iobio. Each variant was annotated in this process. So when a user reviewed a variant (eg. marked it significant), it did not have to make a network request, and the findings page in clin instantly displayed the reviewed variant. However, this was overloading the backend server which was resulting in failure of services. With the recent fixes, the extra annotate variant request is made only after the variant is reviewed and only for that respective variant. So only one request is made thereby not overloading the backend. This causes a slight delay while the response is returned, hence the report-findings page does not immediately display the reviewed variant.

As a solution for this, I have added a progress dialog. It notifies the user that the variant interpretation is in progress.

**Comment by AlistairNWard** [comment]
I'm not entirely sure I understand this. It seems conceptually that adding a significance should be instantaneous and shouldn't require any annotations etc. Is it the saving bit that is causing the problems? Would removing the autosave resolve the issue?

**Comment by adityaekawade** [comment]
I had documented the chain of several function calls in gene.iobio while sending the interpreted variants to clin in this PR: https://github.com/iobio/gene.iobio.vue/pull/558https://github.com/iobio/gene.iobio.vue/pull/558
Each of these function calls seems to be required while adding variants to the findings page in clin. However, as I said in the previous comment,  this process when carried out for all variants, causes an overload of the server and failure of services. Hence, I slightly changed the behavior to make these requests only for one variant at a time, that is when they are reviewed or interpreted. 
I can remove this dialog pop up, but the delay of 10 seconds after adding the review to the variant and not reflecting this on the findings page instantly might not look good.

**Comment by AlistairNWard** [comment]
My source of confusion is why any requests need to be sent out at all? The variant has already been annotated - gene is showing the results. Why is it necessary to reannotate variants that have already been annotated just because you applied a significance?

**Comment by mvelinder** [comment]
I'm also a bit confused as to why this reannotate step needs to happen. Gene.iobio is able to handle this fine when adding significance, not sure why clin.iobio would be any different.

**Comment by adityaekawade** [comment]
There is an additional data property (`self.analysis`) that needs to be handled when launched from clin.iobio. This `self.analysis` is basically an object that is shared between the apps inside clin.iobio and maintains the state of the application.
`self.analysis` keeps track of all the variants by setting an array `self.analysis.payload.variants`. 


When gene.iobio interprets a variant, it adds significance to that respective variant and shows up in the list of variants in the left sidebar. When inside clin.iobio, the selected variant is interpreted but it also needs to update the `self.analysis.payload.variants`. So, In order to correctly interpret and set the data on `self.analysis.payload.variants` , it performs all these additional steps.

**Comment by mvelinder** [comment]
Hmm, instead of discussing the technical details, I guess the real question is: can we avoid this behavior? And can we make it perform like gene.iobio does? If this behavior is somehow unavoidable we can try and deal with that, but if we can remove it and make it behave like gene.iobio does, that would be very much preferred.

**Comment by AlistairNWard** [comment]
But the amount of information that is getting passed around is surely tiny? This is my question. Why is there such a significant effect on timing for such a small amount of information?

**Comment by mvelinder** [comment]
I'm not seeing this anymore on dev.clin.iobio.io - did you address this already @adityaekawade ?

**Comment by adityaekawade** [comment]
Yeah, I removed this dialog pop up in a gene.iobio fix.  There was a breaking change in the clin's variant interpretation behavior after removing the autosave. So while fixing it, I addressed this behavior as well! This should also work on stage.clin

**Comment by adityaekawade** [comment]
@mvelinder , if it looked fine for you, should I close this issue?
