### ISSUE TITLE
Deleting a gene from the "Select phenotypes" step doesn't update in "Review variants"

### ISSUE THREAD

**Issue by mvelinder** [iobio/clin.iobio#267]
Went to "Review variants" step, then back to "Select phenotypes" and removed LMNA from gene list

![image](https://user-images.githubusercontent.com/22081541/88220119-cdfa3200-cc1f-11ea-8a89-8cf518046da1.png)

But LMNA still shows up in the variants list

![image](https://user-images.githubusercontent.com/22081541/88220313-0c8fec80-cc20-11ea-8224-1430274f2e6f.png)

**Comment by adityaekawade** [comment]
A gene will show up in the variants list even if it is deleted from the gene list in the "Select phenotypes" as it is added through the gene sets and not from the gene list. Deleting a gene from the gene list will remove the Gene association in the variants card.

**Comment by adityaekawade** [comment]
Select phenotypes > Delete the gene  "LMNA" > Go to "review variants" > "LMNA" should not show any associations in left sidebar as well as in variants card. 
<img width="862" alt="Screen Shot 2020-07-24 at 10 59 42 AM" src="https://user-images.githubusercontent.com/16284713/88421175-f22f4d80-cd9c-11ea-802b-76da173daeae.png">

Test-  http://dev.clin.iobio.io/

**Comment by mvelinder** [comment]
Yep, this is the correct behavior. My confusion
