### ISSUE TITLE
Case Summary and Phenotypes on "Report findings" don't use full width

### ISSUE THREAD

**Issue by mvelinder** [iobio/clin.iobio#268]
Looks similar to #263 

![image](https://user-images.githubusercontent.com/22081541/88220574-61cbfe00-cc20-11ea-80d5-0feb21363588.png)

**Comment by adityaekawade** [comment]
<img width="1679" alt="Screen Shot 2020-07-24 at 10 17 17 AM" src="https://user-images.githubusercontent.com/16284713/88419376-ef7f2900-cd99-11ea-91dd-430803fa8483.png">
Test: http://dev.clin.iobio.io/
