### ISSUE TITLE
Update Frameshift or Mosaic logos on pdf report

### ISSUE THREAD

**Issue by mvelinder** [iobio/clin.iobio#269]
![image](https://user-images.githubusercontent.com/22081541/88220831-c424fe80-cc20-11ea-823d-467c04192581.png)

I think there are new or better logos for iobio and Mosaic/Frameshift. We can ask @AlistairNWard

**Comment by AlistairNWard** [comment]
![Frameshift_logo_blue](https://user-images.githubusercontent.com/523111/88546368-48dd9700-cfea-11ea-90ec-01005d8a7d60.png)

![Frameshift_icon_blue_sm](https://user-images.githubusercontent.com/523111/88546430-5e52c100-cfea-11ea-92b4-02d6a70a196c.png)

![mosaic_logo](https://user-images.githubusercontent.com/523111/88546501-74f91800-cfea-11ea-8603-ffb940049186.png)

**Comment by adityaekawade** [comment]
<img width="922" alt="Screen Shot 2020-07-28 at 4 00 23 PM" src="https://user-images.githubusercontent.com/16284713/88730702-92fa7180-d0eb-11ea-80e6-531af0c7b0c4.png">

I am adding the new Mosaic logo..
