### ISSUE TITLE
What is the difference between grey and red ! icons?

### ISSUE THREAD

**Issue by mvelinder** [iobio/clin.iobio#272]
![image](https://user-images.githubusercontent.com/22081541/89180322-cb1c0d00-d54e-11ea-900c-7865b8ca8c51.png)

We will want to add hover over text explaining the "error" or problem and what it means for the user

**Comment by adityaekawade** [comment]
Oh! Looks like there was a response failure from the GTR server, hence it showed a grey error icon. I will add a tooltip like the red icon which indicates that no genes are available for that term.
