### ISSUE TITLE
Add info/description of the specifications for the variants csv file

### ISSUE THREAD

**Issue by mvelinder** [iobio/clin.iobio#275]
Users need to know what format the file needs to be in. I would suggest a ? button next to it that gives them this information

![image](https://user-images.githubusercontent.com/22081541/90142470-a3405c80-dd39-11ea-9c42-8b24a36824ff.png)

**Comment by AlistairNWard** [comment]
I thought I used this one and it told me that the csv file is the file output from gene? Also #250 allowed users to input variants via a vcf too, but the user isn't made aware of this. We should make sure with every feature we add, if it isn't completely obvious to a user, some help is provided, e.g. in a ? button as Matt suggested.
