### ISSUE TITLE
Add VCF and TSV variant input options

### ISSUE THREAD

**Issue by mvelinder** [iobio/clin.iobio#279]

**Comment by AlistairNWard** [comment]
It actually says in the modal that you can add vcf files.

**Comment by adityaekawade** [comment]
Do you have a .tsv variant file that I can use to implement and test this functionality?

**Comment by AlistairNWard** [comment]
I just tried to download a vcf from gene.iobio to convert it to a tsv. This needs some effort. Can I recommend that you try and download a vcf from gene.iobio (for the demo data) and then convert to tsv and record any problems along the way. It was extremely unclear to me what variants were getting output and adding significance to variants just seemed to give me random variants. I don't like that you have to click Save, and then download. This should be 1 step. It also causes problems because you click on "comma separated", then click save. Then you can click on vcf, click download, but it downloads a csv. This is all very unclear and pretty unusable.

**Comment by adityaekawade** [comment]
I downloaded VCF from gene.iobio. I can look to convert it to TSV and try to import using that file.  But if I go to gene.iobio and select import variants, there are 2 options to import with tab-delimited files (gemini and just tab-delimited). So I was wondering if these two options have different headers? 
Also, Will has fixed the save- download thing while exporting variants in gene.iobio. It's on stage.gene and will be added to the production version in the next release.

**Comment by adityaekawade** [comment]
I have added the feature to import the variants in .VCF format that are exported from gene.iobio. 

To test:
URL: https://stage.clin.iobio.io/


- Run https://stage.gene.iobio.io/ with demo data(_this feature has a dependency on gene.iobio so it will be added to the prod gene in the next release_) 
- Export the variant in VCF format.
- Launch clin.iobio (https://stage.clin.iobio.io/)
- Click "Load your data" > "Upload configuration file"
- Upload the configuration file. You can download this file from the **example** link in the help text or you should find it in iobio-clin slack channel, or message me and I will share it with you. 
- Upload the downloaded VCF file in the "import variants input field"
- Load
- The review-variants step should load the imported variants.

@mvelinder  @AlistairNWard

**Comment by mvelinder** [comment]
So I exported variants from stage.gene.iobio
![image](https://user-images.githubusercontent.com/22081541/97186583-149f8100-1767-11eb-83ad-d66c96f45ea2.png)
Note, there are 62 genes and 8 variants from this view.

Then I go load in stage.clin.iobio as you describe and jump to the Review Variants step. But I only 6 genes and 7 variants.
![image](https://user-images.githubusercontent.com/22081541/97186891-7f50bc80-1767-11eb-9497-86a753ac7c9e.png)

It's most obvious that something is missing if you look at the GFI1 gene and variant that is saved in the exported VCF, but not imported into clin.iobio. The variant does seem to be in the exported VCF though
```
matt@galago:~/Downloads$ grep GFI1 *vcf
1	92946479	.	G	A	3694.34	.	AB=0.55;ABP=3.87889;AO=145;CIGAR=1X;DP=164;DPB=164;DPRA=0;EPP=4.82236;EPPR=7.35324;GTI=0;LEN=1;MEANALT=1.25;MQM=60;MQMR=60;NS=4;NUMALT=1;ODDS=34.156;PAIRED=0.993103;PAIREDR=1;PAO=0;PQA=0;PQR=0;PRO=0;QA=4327;QR=582;RO=18;RPL=59;RPP=13.9276;RPPR=4.9405;RPR=86;RUN=1;SAF=79;SAP=5.54119;SAR=66;SRF=9;SRP=3.0103;SRR=9;TYPE=snp;technology.ILLUMINA=0.848276;CSQ=A|synonymous_variant|LOW|GFI1|ENSG00000162676|Transcript|ENST00000294702|protein_coding|4/7||ENST00000294702.5:c.465C>T|ENSP00000294702.5:p.Cys155=|715|465|155|C|tgC/tgT|rs11164605|1||-1||HGNC|4237||||0.9189|0.944|0.889|0.9752|0.8091|0.9611|0.9286|0.8132|0.862|0.9193|0.9088|0.8818|0.9657|0.7789|0.7987|0.8402|0.9494|0.9752|EAS|benign||1|||||,A|synonymous_variant|LOW|GFI1|ENSG00000162676|Transcript|ENST00000370332|protein_coding|4/7||ENST00000370332.1:c.465C>T|ENSP00000359357.1:p.Cys155=|784|465|155|C|tgC/tgT|rs11164605|1||-1||HGNC|4237||||0.9189|0.944|0.889|0.9752|0.8091|0.9611|0.9286|0.8132|0.862|0.9193|0.9088|0.8818|0.9657|0.7789|0.7987|0.8402|0.9494|0.9752|EAS|benign||1|||||,A|synonymous_variant|LOW|GFI1|ENSG00000162676|Transcript|ENST00000427103|protein_coding|4/7||ENST00000427103.1:c.465C>T|ENSP00000399719.1:p.Cys155=|622|465|155|C|tgC/tgT|rs11164605|1||-1||HGNC|4237||||0.9189|0.944|0.889|0.9752|0.8091|0.9611|0.9286|0.8132|0.862|0.9193|0.9088|0.8818|0.9657|0.7789|0.7987|0.8402|0.9494|0.9752|EAS|benign||1|||||,A|downstream_gene_variant|MODIFIER|GFI1|ENSG00000162676|Transcript|ENST00000483490|processed_transcript||||||||||rs11164605|1|2068|-1||HGNC|4237||||0.9189|0.944|0.889|0.9752|0.8091|0.9611|0.9286|0.8132|0.862|0.9193|0.9088|0.8818|0.9657|0.7789|0.7987|0.8402|0.9494|0.9752|EAS|benign||1|||||,A|regulatory_region_variant|MODIFIER|||RegulatoryFeature|ENSR00000009835|promoter||||||||||rs11164605|1|||||||||0.9189|0.944|0.889|0.9752|0.8091|0.9611|0.9286|0.8132|0.862|0.9193|0.9088|0.8818|0.9657|0.7789|0.7987|0.8402|0.9494|0.9752|EAS|benign||1|||||;AF=0.849677;AN=31000;AC=26340;nhomalt_raw=11383;AF_popmax=0.965385;AF_fin=0.776583;AF_nfe=0.809864;AF_oth=0.828067;AF_amr=0.903148;AF_afr=0.923193;AF_asj=0.906897;AF_eas=0.965385;IOBIO=start#92946479|end#92946480|geneName#GFI1|transcript#ENST00000370332.1|isUserFlagged#Y|filtersPassed#userFlagged|freebayesCalled#.|type#snp|impact#low|highestImpact#MODIFIER|highestImpactInfo#modifier downstream_gene_variant in ENST00000483490|consequence#synonymous variant|afExAC#.|af1000G#.|afgnomAD#0.862|inheritance#.|polyphen#.|SIFT#.|REVEL#.|rsId#rs11164605|clinvarClinSig#benign|clinvarTrait#.|HGVSc#ENST00000370332.1:c.465C>T|HGVSp#ENSP00000359357.1:p.Cys155=|zygosityProband#HOM|altCountProband#31|refCountProband#0|depthProband#31|bamDepthProband#.|zygosityMother#HOM|altCountMother#47|refCountMother#0|depthMother#47|bamDepthMother#.|zygosityFather#HOM|altCountFather#45|refCountFather#0|depthFather#45|bamDepthFather#.	GT:DP:RO:QR:AO:QA:GL	1/1:31:0:0:31:997:-90.0162,-9.33193,0	1/1:47:0:0:47:1419:-127.985,-14.1484,0	1/1:46:0:0:45:1294:-116.661,-13.5464,0	0/1:40:18:582:22:617:-43.7517,0,-40.6346
```

So the GFI1 variant should definitely be imported.

It seems gene.iobio exports all variants that are in the variant panel, whether they have had a significance assigned or not. For instance, I can find the APOB variant in the exported VCF, even though I haven't assigned it a signifcance:
```
matt@galago:~/Downloads$ grep APOB *vcf
2	21232803	.	TG	CA	5810.48	.	AB=0.440994;ABP=7.87925;AO=128;CIGAR=2X;DP=218;DPB=219.5;DPRA=0;EPP=11.2212;EPPR=0;GTI=0;LEN=2;MEANALT=1.75;MQM=60;MQMR=0;NS=4;NUMALT=2;ODDS=41.4384;PAIRED=1;PAIREDR=0;PAO=1.5;PQA=44.5;PQR=0;PRO=0;QA=4464;QR=0;RO=0;RPL=56;RPP=7.35324;RPPR=0;RPR=72;RUN=1;SAF=63;SAP=3.07816;SAR=65;SRF=0;SRP=0;SRR=0;TYPE=mnp;technology.ILLUMINA=0.554688;OLD_MULTIALLELIC=2:21232803:TG/CA/CG;CSQ=CA|missense_variant|MODERATE|APOB|ENSG00000084674|Transcript|ENST00000233242|protein_coding|26/29||ENST00000233242.1:c.6936_6937inv|ENSP00000233242.1:p.Ile2313Val|7064-7065|6936-6937|2312-2313|DI/DV|gaCAtt/gaTGtt|rs386643884|1||-1||HGNC|603|||||||||||||||||||||||benign&likely_benign||1|||||;IOBIO=start#21232803|end#21232805|geneName#APOB|transcript#ENST00000233242.1|isUserFlagged#.|filtersPassed#high|freebayesCalled#.|type#mnp|impact#moderate|highestImpact#.|highestImpactInfo#.|consequence#missense variant|afExAC#.|af1000G#.|afgnomAD#.|inheritance#.|polyphen#.|SIFT#.|REVEL#.|rsId#rs386643884|clinvarClinSig#benign/likely benign|clinvarTrait#Familial hypercholesterolemia, Familial hypercholesterolemia 1, Familial hypercholesterolemia 2, Hypobetalipoproteinemia, familial, 1, Familial hypobetalipoproteinemia|HGVSc#ENST00000233242.1:c.6936_6937inv|HGVSp#ENSP00000233242.1:p.Ile2313Val|zygosityProband#HET|altCountProband#20|refCountProband#0|depthProband#20|bamDepthProband#.|zygosityMother#HET|altCountMother#24|refCountMother#0|depthMother#24|bamDepthMother#.|zygosityFather#HET|altCountFather#27|refCountFather#0|depthFather#27|bamDepthFather#.	GT:DP:RO:QR:AO:QA:GL	1/.:46:0:0:20:726:-130.099,-72.131,-64.9063	1/.:50:0:0:24:761:-120.495,-59.2294,-52.0047	1/.:65:0:0:27:838:-152.389,-85.7622,-77.0323	1/1:57:0:0:57:2139:-192.712,-17.1587,0
```

In the future we'll also want to have gene exported VCFs maintain the user provided significance and notes when importing back into clin.iobio (or gene.iobio again). But for now at a minimum the VCF variants should be showing up as expected.

**Comment by AlistairNWard** [comment]
I would argue that's not for the future. The purpose of the export is to be able to reimport all the information necessary for gene, so the significance absolutely needs to be retained (we can worry about notes later).

I think we should also include a note when exporting about what is going to be exported. It used to be the case that the only variants that were exported were _bookmarked_ variants, but we got rid of bookmarks. So, as evidenced by Matt's comments, it is not clear to the user exactly what is going to be exported. We should provide a note that explains exactly what is going to be exported, and even give a quick summary (e.g. n variants in m genes will be exported).

**Comment by mvelinder** [comment]
Maybe I was being too "future" focused. It is a core functionality for export/import across our apps. I agree it should be addressed in this version. I added an issue here @AlistairNWard @adityaekawade https://github.com/iobio/clin.iobio/issues/305

**Comment by mvelinder** [comment]
If notes are simply a text string added as a VCF annotation (that seems to be how gene is exporting things), then notes should also be relatively easy to add along with significance. I'd say we try to do both now.

**Comment by AlistairNWard** [comment]
Notes are more than just a text string - they are an ordered, timestamped list of strings. But if it is simple, we should do both now.

**Comment by adityaekawade** [comment]
@mvelinder I want to reproduce the above scenario. Did you use the demo data to load gene.iobio? Also can you share the list of genes added or the VCF file which was downloaded?

**Comment by adityaekawade** [comment]
The reviewed variants along with the notes should also be shown when importing variants. But I will create it as a separate issue as the imported variants that are interpreted should also be shown on the "report-findings" page of the clin.

**Comment by adityaekawade** [comment]
@mvelinder  @AlistairNWard 

The interpretation and notes will now be shown for the reviewed imported variants. 

To test: 

- Run gene.iobio (https://stage.gene.iobio.io/) with demo data
- Review some variants by attaching significance or by adding notes.
- export the variant in both VCF and CSV format.
- Launch clin (https://stage.clin.iobio.io/)
- Click "Upload configuration file"
- Upload the configuration file
- Upload the downloaded VCF file
- Load
- The review-variants step should load the imported variants. Reviewed variants should be tagged correctly (correct significance)
- Go to the report findings page. The reviewed variants that were imported should be displayed.
- Perform the same steps with the downloaded CSV file.

**Comment by AlistairNWard** [comment]
Just for fun, for the configuration file, I included the csv I just downloaded from gene (since I don't have a configuration file handy), and the vcf I just downloaded from gene. clin opens fine, but with a completely different set of data. I have variants in a bunch of genes, none of which are in the downloaded vcf or csv. Seems like this isn't what should happen

**Comment by adityaekawade** [comment]
Oh! That had bypassed a validation check for the csv config file. But it could not set the custom data and instead launched clin with demo data. Thanks for catching this. 
I have made updates to the validation check now and it should show an error if the headers do not match. 
![Screen Shot 2020-11-02 at 1 42 52 PM](https://user-images.githubusercontent.com/16284713/97922860-f7902280-1d11-11eb-949e-85d4da200e2e.png)
Can you please try it again?

**Comment by AlistairNWard** [comment]
Yep, all the correct values are populated from both vcf and csv downloads.

One observation, if I put the gene output csv as the config file, that error does appear. I wasn't paying too much attention, and just added the vcf as well, and this made the error attached to the config file disappear, so I actually missed it the first time. The Load button was still disabled, but it would be good for the error to persist until addressed.
