### ISSUE TITLE
Release banner

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/clin.iobio#281]
On the landing page (and in blog posts etc), we should include a banner explaining the purpose of this release, e.g. clinician users use the demo data, bioinformaticians can use their own data (via URLs), and discuss integrations, e.g. Mosaic or with your own institutions systems.

**Comment by adityaekawade** [comment]
I have created a banner with the following text: 
"We are happy to announce the first public release of clin.iobio. You can get started by running the demo data or use your own data (via URLs). To discuss integrations of clin.iobio with Mosaic or with your own institution systems feel free to contact us."

I just thought we can keep it a general announcement, so if a clinician has data via URLs he can use that feature, but feel free to change it. 

@AlistairNWard let me know if you want to have a "launch Mosaic" button or any other call to action in this banner. 
 
<img width="1680" alt="Screen Shot 2020-08-20 at 9 19 49 AM" src="https://user-images.githubusercontent.com/16284713/90798226-84f0d880-e2c6-11ea-8a42-2978a8c73432.png">

**Comment by adityaekawade** [comment]
Also, I noticed that the video shows the demonstration of the app by launching from Mosaic. That might be confusing to the users.

**Comment by AlistairNWard** [comment]
I think we want to be a little more explicit and make it a bit more prominent. We want to be sure that the different target users quickly find their way in. So my recommendations are:

**Comment by adityaekawade** [comment]
Sounds good! How to launch the Platinum Exomes project, should that link out to Mosaic?

**Comment by AlistairNWard** [comment]
Yes, rather than separate links at the end for contact us and Mosaic, we could include one contact us link, and then make Mosaic in the text a link?

We are happy to announce the public, beta release of clin.iobio. Please give it a try and contact us with any feedback or questions about integrating with your own data.
Try it out? Click "Run with demo data" to try out the tool with a public dataset
Have your own data? Click "Load your data" and provide URLs to BAM and VCF files
Integrate with your own system? Clin.iobio can be integrated with a data management system for easy launch. For example, launch clin.iobio from the Platinum Exomes project in Frameshift's Mosaic (LINK)

Contact us (LINK)
