### ISSUE TITLE
Variant list does not adjust to selected phenotypes

### ISSUE THREAD

**Issue by azankl** [iobio/clin.iobio#288]
Love the iobio apps, so wanted to try out clin.iobio. I used the demo data and selected  'bilateral postaxial polydactly' as the phenotype term, then only chose to include the HPO term "Bilateral postaxial polydactyly - [ HP:0006136 ]". This returned only one possible gene: GLI3. Nevertheless, clin.iobio reports 9 variants in PRX, SCN8A and other genes. So looks like the gene list is not correctly updating to the selected phenotypes.

**Comment by AlistairNWard** [comment]
Thanks for bringing up this issue, Andreas. This is in the correct behaviour, but we haven't sufficiently explained what is actually happening. The "Review Variants" step in the workflow is reviewing all of the variants in a predefined set of genes. When not using the demo data, you will be prompted to supply a list of genes, or a list of variants (which will result in a list of genes that the variants are in). Typically these would be a set of genes that harbor variants that may appear interesting (e.g. rare de novo variants etc.). The gene list generated in the "Select Phenotypes" step is used to annotate any variants with any gene associations with this list. For example, this is the PRX gene from the demo data:

![Screen Shot 2020-08-26 at 9 01 51 PM](https://user-images.githubusercontent.com/523111/91371642-8ac34e00-e7df-11ea-89f5-c9cd3cc1cc72.png)

I have highlighted the gene associations section of the variant detail panel. There are no gene associations listed, as the only gene found to associate with the phenotypes you entered was GLI3. If PRX was associated with the phenotypes, the relevant associations would be listed here. I selected a couple of terms from the predefined clinical note, and PRX now looks like:

![Screen Shot 2020-08-26 at 9 06 36 PM](https://user-images.githubusercontent.com/523111/91371838-1d63ed00-e7e0-11ea-9726-0d7d462cd1d3.png)

You can now see that PRX was returned by GTR, Phenolyzer, and HPO as being associated with entered terms, and the left panel indicates variants that are in genes with associations based on the entered terms.

Our experience has been that only looking at variants in the list of genes identified in the Select Phenotypes step often misses variants that would be important to review. So, in this beta release of clin.iobio, we require that you define a list of genes (or variants) which will be reviewed and use the Select Phenotypes to annotate these variants providing evidence for a variants potential role.

It is our intention to include an extra step in the workflow that would let you review the top genes returned in Select Phenotypes (issue #252), but we didn't include that in this release. Hopefully this explanation makes sense, and if you have any thoughts or comments, please share them. We'd really like to hear opinions on this new app. Thanks again for your comment.

**Comment by AlistairNWard** [comment]
@azankl I am going to close this issue as this has been updated. As an example:
1. Open clin.iobio and use the demo data
2. Click on Review variants. There are 8 genes analysed, and no variants have gene associations
3. Go to the Select Phenotypes step and add Charcot-Marie-Tooth disease as the clinical note and generate a gene list
4. Select the top 5 genes at the top of the table
5. Return to Review variants and the top 5 genes have been pulled across and variants within them analysed.
