### ISSUE TITLE
clin.iobio should be a link to the homepage

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/clin.iobio#289]
When data has been entered and you're in the main clin workflow, it says clin.iobio in the top left corner. This should be a link back to the clin.iobio landing page.

**Comment by adityaekawade** [comment]
Clicking the title from the main clin workflow will now link back to clin.iobio landing page. However, the buttons on the landing page will be updated (As shown in the screenshot below) to either resume the analysis or start a new analysis 

<img width="752" alt="Screen Shot 2020-08-27 at 2 37 10 PM" src="https://user-images.githubusercontent.com/16284713/91498236-4a61df80-e874-11ea-9233-679b65ab6a3e.png">

You can test it on: http://dev.clin.iobio.io/

**Comment by AlistairNWard** [comment]
Yes this works, and I like the resume analysis option!
