### ISSUE TITLE
Launch clin with no inputs

### ISSUE THREAD

**Issue by adityaekawade** [iobio/clin.iobio#298]
Ability to launch clin with no inputs (gene sets or variant sets) from Mosaic and custom data

**Comment by adityaekawade** [comment]
I wanted a quick suggestion on the text. If you launch clin without any input and go straight to "review variants" page, it will show a warning dialog saying that no input was added when launching the app. Please see the screenshot below.
Clicking the "Generate genelist" button will take to step 2 (select phenotypes) to select genes that will be analyzed here. 
Please let me know if any changes that need to be made in this text or button title. 
![Screen Shot 2020-10-16 at 8 49 20 AM](https://user-images.githubusercontent.com/16284713/96280655-1611c200-0f8d-11eb-8c9f-c1842f5e7590.png)
@AlistairNWard @mvelinder

**Comment by adityaekawade** [comment]
To test:

- From the landing page click Load your data > Upload configuration file
- Load button should be disabled
- Upload the config file in the Data input configuration field
- Load button should now be enabled
- Click the load button
- Go to step 3 (Review variants)
- A warning dialog should be shown to indicate that this step requires genes or variants.
- Clicking the button "Generate gene list" should take you to step 2 (Select phenotypes)
- Generate a gene list or add genes (eg. PRX)
- Go to step 3 (Review variants)
- The genes should start analyzing

Test URL: https://stage.clin.iobio.io/

**Comment by mvelinder** [comment]
Those steps worked as you described them.

**Comment by AlistairNWard** [comment]
Do you have a demo config file I can use?

**Comment by AlistairNWard** [comment]
Ok, here is an alternative wording, if you want one.

No variants were uploaded to this analysis for review. Genes of interest can be added in the _Select Phenotype_ step, which will allow variants in those genes to be reviewed.

The button should be _Generate gene list_

**Comment by adityaekawade** [comment]
Updated!
