### ISSUE TITLE
Reviewed variants not maintained at top when adding new genes

### ISSUE THREAD

**Issue by mvelinder** [iobio/clin.iobio#304]
Launch stage.clin.iobio.io
Add some phenotype terms
Go to review variants, allow variants to load, mark some variants are significant
Go back to phenotype entry step, add genes manually
Go back to review variants and previously marked significant variants are not at the top of the variant panel list anymore

![image](https://user-images.githubusercontent.com/22081541/97183735-c177ff00-1763-11eb-9608-a69015de439f.png)

**Comment by adityaekawade** [comment]
@mvelinder  This should be fixed. You can try it on stage.clin.

**Comment by mvelinder** [comment]
Looks good in my testing!
