### ISSUE TITLE
Maintain user assigned significance and notes across exported/imported files

### ISSUE THREAD

**Issue by mvelinder** [iobio/clin.iobio#305]
Use case where a user does an analysis in gene.iobio, marks a bunch of variants as significant and adds notes, then exports the analysis as a VCF or CSV and imports it back into clin.iobio. The same significances and notes should appear in clin.iobio

**Comment by adityaekawade** [comment]
This issue was addressed in the PR: https://github.com/iobio/clin.iobio/pull/310
