### ISSUE TITLE
Focus needs to be placed on a gene

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/clin.iobio#307]
1. Launch clin from Mosaic with no input. 
2. Add some phenotype and generate some genes
3. Review variants processes the genes, but if there are no interesting variants, the left menu is empty and the main screen is blank since no variant is selected.

If there are no variants, just pick the top gene and show the variants in that gene in the main panel

**Comment by adityaekawade** [comment]
@AlistairNWard This is ready for testing on stage.clin

**Comment by AlistairNWard** [comment]
This is a test run from Mosaic. How do I test on clin? If I just include stage in the url, I just get to the landing page

**Comment by adityaekawade** [comment]
Launch clin from Mosaic with no inputs and then do the URL trick to change clin.iobio.io to stage.clin.iobio.io.. It should not take you to the landing page.

**Comment by AlistairNWard** [comment]
Works for me
