### ISSUE TITLE
Add autocomplete to Add Genes functionality

### ISSUE THREAD

**Issue by mvelinder** [iobio/clin.iobio#313]
Adding genes via 
![image](https://user-images.githubusercontent.com/22081541/98011169-c0268200-1db4-11eb-8ee4-e559cb708652.png)
only allows freeform text

It would be nice to have autocomplete functionality for single genes
And still allow copy/paste gene lists, similar to gene.iobio

**Comment by mvelinder** [comment]
We should also address the ambiguity of "Find gene" in this issue. Probably just rework the entire area. 
1) Change Find gene to "Search in gene list" or something similar
2) Add functionality for adding a single gene (similar to gene.iobio)
3) Change + Add to "Add gene list" or something similar for the copy/paste functionality

**Comment by adityaekawade** [comment]
Good point, looking at just the screenshot you have posted above, it seems like the user will be more inclined to type the gene name in the input field and then click the "+ Add" button assuming it will add the gene to the gene list.  Whereas in reality, both are completely different features.

**Comment by adityaekawade** [comment]
Also, the autocomplete can be added when importing genes for custom data. 
![Screen Shot 2020-11-03 at 8 16 24 AM](https://user-images.githubusercontent.com/16284713/98012384-e399fe80-1dad-11eb-9c1d-b4d8e8258005.png)

**Comment by adityaekawade** [comment]
Test: http://dev.clin.iobio.io/

Also added the autocomplete genes while importing clin data through the config file. 
To test: Load your data > Upload configuration file > Select genes with autocomplete or click the "copy" icon to change the mode to paste a list of genes. 
![Screen Shot 2020-12-01 at 10 28 23 AM](https://user-images.githubusercontent.com/16284713/100781606-15f44700-33c0-11eb-86f0-b35cc050ab11.png)
