### ISSUE TITLE
Make gene name more prominent in findings

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/clin.iobio#320]
Comment from EIEE review session:

The gene name should be more prominent in the clin.iobio findings. Typically, people will be looking at the variants in the findings and will identify the variant by the gene it is in. The gene name should be very prominent in the table.

**Comment by adityaekawade** [comment]
I tried a couple of variations to highlight the gene name on the findings page. 

1. The variant information goes inside an expansion panel which is open by default. The gene name is on the panel header
![Screen Shot 2020-11-16 at 10 23 31 AM](https://user-images.githubusercontent.com/16284713/99292400-04267780-27f6-11eb-8933-520ef9f2d559.png)


2. Reorganized to show the gene name first. 
![Screen Shot 2020-11-16 at 8 56 09 AM](https://user-images.githubusercontent.com/16284713/99292626-55cf0200-27f6-11eb-868a-ea19aeef2a8c.png)

Would like to know which is preferred or any other suggestion regarding the text. I prefer the first one.

**Comment by AlistairNWard** [comment]
I think I prefer the first one too. My only comment would be one of colour. The eye is immediately drawn to the bright badges, so when I open e.g. the first image, I immediately see the gene associations and the significance. The gene should be something my eye is drawn to, so I would recommend something more prominent to attract attention

**Comment by adityaekawade** [comment]
You can test this on http://dev.clin.iobio.io/

**Comment by mvelinder** [comment]
And here I preferred the second one... I'm good with the first though
