### ISSUE TITLE
Single entry input

### ISSUE THREAD

**Issue by adityaekawade** [iobio/clin.iobio#321]
- The user enters a clinical note. 
- The app parses the note and extracts the general terms. 
- This general term will be used to search in all the tools. If there is no direct match with the HPO term, clinphen will be used to match synonyms. 
- We will also provide an advanced mode that will have options to refine and select terms.
- For terms that do not have a direct match or a general term, users will have to select the advance mode and select terms. 

@AlistairNWard @mvelinder Please add comments to this discussion if I have missed anything.

**Comment by mvelinder** [comment]
Sounds like a good summary. We can talk about "advanced mode" more, but I'm mostly thinking of it as a dropdown for refining terms, not a full on different user mode. I think the clinphen term matching is awesome to use as is for now. And we can default select the top (general) term for the disorder as well. 

Hopefully just shuffling some components and workflow steps, but the pieces seem to be there :+1:

**Comment by AlistairNWard** [comment]
This looks right to me @adityaekawade, but I'll add a couple of additional clarifications. "Advanced mode" is exactly what we have now.

- The user enters a clinical note.
- The app parses the note and extracts the general terms.
- This general term will be used to search in all the tools. If there is no direct match with the HPO term, clinphen will be used to match synonyms.
- For terms that do not have a direct match or a general term, "users will have to select the advance mode and select terms". Alternatively, for now, we could just parse the returned terms and automatically select the term closest to the entered term. This could simply be a distance metric between the entered term and each available term, and we pick the one with the smallest value
- The user is presented with a summary in the modal. E.g. the entered term, the terms that have been automatically selected by us for each tool, and indicated how many "related" terms are also available for each term. E.g. if you enter Treacher Collins syndrome, you will told 1. You entered "Treacher Collins sydrome"; 2. we picked the terms "Treacher Collins syndrome" from GTR, "Treacher collins syndrome" from Phenolyzer, and "Mandibulofacial dysostosis [HPO:0005321]" from HPO; that there were 6, 7, and 0 related terms available from the 3 tools.
- Given that the modal makes it clear what is picked, but that there are also other available terms, the user has a button to proceed with the terms we selected, or choose advanced mode to refine their choice.
- We will also provide an advanced mode that will have options to refine and select terms. This is just going to what we already have in clin where the user can look through the other terms

**Comment by adityaekawade** [comment]
@AlistairNWard @mvelinder , I wanted to give a quick update. And I feel this should make it easy to select terms and search across tools. I have made a few tweaks while developing this, as I felt this will make the workflow easier for any user. Let me know what you think.. 

1.  The user enters a clinical note. The app parses the note and extracts the terms, which are presented for selection (_Let's call this "Basic-page" for simplicity_). 
A message is displayed that selecting terms will match the closest terms in the tool or they can use the advance mode by clicking the "refine terms" button. 
![Screen Shot 2020-12-03 at 2 56 05 PM](https://user-images.githubusercontent.com/16284713/101099188-1edc4880-3579-11eb-9bda-f91296c8c963.png)


2. The user can make a selection and can directly proceed to review the selected terms. 
![Screen Shot 2020-12-03 at 2 56 28 PM](https://user-images.githubusercontent.com/16284713/101099495-97430980-3579-11eb-9bbc-dc4b6774ac55.png)
The review page shows the terms selected in each of the tools based on the selection. Clicking the back button takes him back to the _basic-page_. 

Clicking the "edit" button next to each tool on the Review page will allow the user to make any changes for that particular tool. Notice the "Cancel" and "Save" buttons instead of "back" and "next" to indicate the "edit" mode.  

![Screen Shot 2020-12-03 at 3 23 03 PM](https://user-images.githubusercontent.com/16284713/101100507-7b406780-357b-11eb-89ef-13f040d5d0d8.png)


3.  If the user clicks the "Refine terms" button from the "_Basic-page_" he is taken to the advance mode (_the workflow that we have now_)

![Screen Shot 2020-12-03 at 2 57 25 PM](https://user-images.githubusercontent.com/16284713/101099861-67e0cc80-357a-11eb-88da-9cc87a195ac9.png)

Now since he had already selected two terms from the "Basic_page", the state is saved and the user can look for the selected terms in the advanced mode. He can also make additional selections here (Hammertoe was selected in basic-page and Peripheral demyelination is the new selection).   


![Screen Shot 2020-12-03 at 3 19 08 PM](https://user-images.githubusercontent.com/16284713/101100196-ee95a980-357a-11eb-9b18-bbabdcd51c0e.png)

Clicking "Next" takes the user to the "Review page" to review all the selections or to make changes. 

I am still trying a couple of things and I should put this on dev.clin tomorrow for testing..

**Comment by AlistairNWard** [comment]
Thanks Adit. Why is Charcot Marie Tooth not extracted from the clinical note?

Also, if the number of terms extracted is not too large, should we select them all by default? This way, the user can enter the clinical note, then click Review and get to the gene list quickly with a minimum of clicks

**Comment by adityaekawade** [comment]
"Charcot Marie Tooth" is extracted. I had scrolled down to select these two terms.. 
Yeah, If the number of extracted terms is less than 5 we can select all by default. I will try this and see how it works.

**Comment by adityaekawade** [comment]
Available to test on http://dev.clin.iobio.io/

**Comment by adityaekawade** [comment]
I have created some prototypes for the new version of genepanel based on the single entry feature: https://docs.google.com/document/d/1Z81D1dQ3Eaz5H09Yoa2jREcMBb0D7UPZyqFybiDHtew/edit#heading=h.h6kl6zgp8qfc

**Comment by AlistairNWard** [comment]
Thanks @adityaekawade , I'll take a look

**Comment by mvelinder** [comment]
dev.clin is looking great @adityaekawade ! I don't really have any issues to address.

**Comment by adityaekawade** [comment]
Sounds good! I will merge this to stage.

**Comment by AlistairNWard** [comment]
I made a couple of comments, but everything looks generally good.

**Comment by adityaekawade** [comment]
Closing this as we are updating it with new version.
