### ISSUE TITLE
 HPO terms not being selected

### ISSUE THREAD

**Issue by mvelinder** [iobio/clin.iobio#337]
This has happened off and on for me, @adityaekawade mentioned it might be a timing issue, but I ran into it again just now

This is using the demo data from production clin.iobio.io where no HPO terms are selected by default
![image](https://user-images.githubusercontent.com/22081541/107692285-cce72b80-6c69-11eb-9160-bec38b220c0e.png)

**Comment by adityaekawade** [comment]
This is on my priority list and it will be updated with a fix this week.

**Comment by AlistairNWard** [comment]
Thanks @adityaekawade . I have observed this as well

**Comment by adityaekawade** [comment]
I have fixed this. You can try on dev.clin
