### ISSUE TITLE
Clinical term appears as input even if not run

### ISSUE THREAD

**Issue by adityaekawade** [iobio/clin.iobio#343]
Frrom Al: 
Type a term in the entry field and move to select terms from GTR etc. X out of the modal, so no searching on terms is performed. The clin page shows the search term as an input that can be edited, but a search for genes was never made on this input. If the user cancels the search, the search term should not appear as an input.

This persists through clin, e.g. a term that wasn't actually searched appears as blank in the report

Genepanel issue: https://github.com/iobio/genepanel.iobio/issues/367

**Comment by AlistairNWard** [comment]
With the updated modal, there is a cancel button. If you hit cancel, clin goes ahead and generates a gene list anyway. If you hit cancel, you should just go back to the gene list generation page, nothing should be evaluated, and the terms that were included should not appear in the Inputs field

**Comment by adityaekawade** [comment]
I changed the behaviour so that when you X out of the modal, the search term does not appear as input.  But looking at the code it seemed like earlier we wanted the behaviour to show the input term when we closed the modal. 

I also fixed the above bug, so if you hit cancel it will just dismiss the modal and no terms will appear in the Inputs field.
Test on dev.clin

**Comment by AlistairNWard** [comment]
Do you know why the code was like it was? I can't think why we would have want the input to show if you cancel out of something.

**Comment by adityaekawade** [comment]
I don't remember the reason, but maybe to keep track of note that was entered even though we did not search on the extracted terms. 
New behaviour makes more sense.
