### ISSUE TITLE
Show gene associations in the left menu

### ISSUE THREAD

**Issue by adityaekawade** [iobio/clin.iobio#347]
From Al: When the user looks at the variants in the left menu, we should indicate if the variant is in a gene with associations. I don't think we want to get too clever about trying to show what associations, just that they exist. The ordering of the variants could also be modified based on whether they have associations or not

Genepanel issue: https://github.com/iobio/genepanel.iobio/issues/375

**Comment by AlistairNWard** [comment]
I can't replicate this. Not sure why I saw it when I made the issue, but when I look now, there is an indication in the left menu. I added #717 to the gene.iobio repo about variant ordering that would be nice to address.

**Comment by adityaekawade** [comment]
Variant order will be addressed in gene. And since there is an indication in the left menu for gene association should we close this issue?
