### ISSUE TITLE
Cannot delete an input term

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/clin.iobio#348]
The user could add a term and generate a list of genes. You can edit the input and change the selected terms, but you should also be able to just delete an input and have the gene list updated with the results from that input removed

**Comment by adityaekawade** [comment]
You should now be able to delete an added note. 

It will show a warning to confirm the deletion 
![Screen Shot 2021-02-19 at 1 45 31 PM](https://user-images.githubusercontent.com/16284713/108565159-14e4fe80-72b9-11eb-84af-f0ffa9f3d620.png)

And a loading screen while the gene list gets reorganized. 
![Screen Shot 2021-02-19 at 1 45 48 PM](https://user-images.githubusercontent.com/16284713/108565195-24644780-72b9-11eb-81f8-e5c23b956a37.png)

Test: https://dev.clin.iobio.io/

**Comment by AlistairNWard** [comment]
This works nicely
