### ISSUE TITLE
Gene associations don't update in the report

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/clin.iobio#351]
Reproduce on demo data:
1. Open demo data, and go straight to review variants
2. Mark the PRX variant as significant and it appears in the report. The gene associations are empty since there is no gene list
3. Go to the phenotype step, and add the demo note
4. Go to review variants and now the PRX has gene associations
5. Go to the report and the gene associations are still blank

Make sure that the report table remains up to date.

**Comment by adityaekawade** [comment]
This was a good find! And the issue was kind of tricky as the gene object was quite nested. 
It should be fixed now. Try it on: https://dev.clin.iobio.io/

**Comment by AlistairNWard** [comment]
Yep, this is working properly now
