### ISSUE TITLE
Pedigree clarity

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/clin.iobio#354]
1. The pedigree doesn't appear to be centred wrt to the titles

![Screen Shot 2021-02-22 at 9 48 19 AM](https://user-images.githubusercontent.com/523111/108724289-2ade0380-74f3-11eb-813c-ccd1f60deab2.png)

2. Is the sample name and relationship passed as a single string, e.g. "Proband NA12878", or is two strings? If it's two, it might make sense to put these on two lines.
3. Is the styling of the pedigree inherited? There is still some trouble by some users identifying which sample  the data refers to. Can we try increasing the blue stroke thickness on the selected individual to make it clearer?
4. Include a tooltip to explain the pedigree chart. This is what appears in Mosaic

![Screen Shot 2021-02-22 at 9 52 48 AM](https://user-images.githubusercontent.com/523111/108725014-f0289b00-74f3-11eb-8fee-1b40887e7e46.png)

5. Is it clear that this page is divided into rows. It might be worth trying to design this to be clearer. I'll try and make some mockups

**Comment by adityaekawade** [comment]
Sample name and relationship can be split into two different lines. Also increased the stroke thickness of the selected individual
<img width="297" alt="Screen Shot 2021-03-05 at 2 53 01 PM" src="https://user-images.githubusercontent.com/16284713/110183007-c8beb180-7dc2-11eb-88b7-a45bf536edd9.png">


Added the tooltip to explain the pedigree chart
<img width="381" alt="Screen Shot 2021-03-05 at 2 53 15 PM" src="https://user-images.githubusercontent.com/16284713/110183154-19cea580-7dc3-11eb-9a36-b652082753a8.png">


I can add horizontal lines or dividers to make it more clear that the page is divided into rows. Also, are you planning to do mockups?

**Comment by AlistairNWard** [comment]
Totally forgot I mentioned mockups! Maybe some very subtle horizontal dividers is worth trying. I don't think we'd want anything too bold, so I think that would be enough

**Comment by adityaekawade** [comment]
Made few tweaks on the review page. Test: https://dev.clin.iobio.io/

![Screen Shot 2021-03-08 at 10 10 23 AM](https://user-images.githubusercontent.com/16284713/110364083-33a4fe00-7ff8-11eb-826e-dd8e222beb2f.png)
![Screen Shot 2021-03-08 at 10 10 40 AM](https://user-images.githubusercontent.com/16284713/110364086-34d62b00-7ff8-11eb-8244-a08584969894.png)

**Comment by AlistairNWard** [comment]
Works for me
