### ISSUE TITLE
Support for HPO terms

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/clin.iobio#359]
We should explicitly support the case where HPO terms are included in the note. I see two cases that we should handle, but this is just suggestions to start discussion. These are 1) there are HPO ids embedded in the text of the note, but there are terms as well as HPO; 2) the note is just a list of HPO ids (or HPO ids along with their terms). I suggest we do something like this. If any HPO ids are detected in the note, we include this observation in the modal, and give the users a choice. They can choose to only select the HPO terms which were included in the note:

![Asset 5](https://user-images.githubusercontent.com/523111/109311682-18760980-7814-11eb-8337-4021dc888c88.png)

The search on the note will have resulted in GTR / Phenolyzer terms and probably found additional HPO terms. The user could also choose to pull in all terms.

![Asset 4](https://user-images.githubusercontent.com/523111/109311844-4c512f00-7814-11eb-9e53-9fcdb2f63014.png)

Obviously, they can manually add or remove terms, or refine terms as usual, but this would mean 1) minimal change to the way things currently work; 2) the only additional click the user has to do is to change the radio button if they want all results rather than just the HPO terms they entered; 3) makes it easy to generate a gene list just using HPO terms.

**Comment by adityaekawade** [comment]
Yeah, this looks good and should work consistently in how it is currently set up.

**Comment by adityaekawade** [comment]
It should now detect hpo terms and show the options to either select only inputted HPO terms or terms from all sources.
![Screen Shot 2021-03-03 at 11 49 42 AM](https://user-images.githubusercontent.com/16284713/109864221-6b3a3180-7c17-11eb-9519-2b29d735b0b0.png)
![Screen Shot 2021-03-03 at 11 50 00 AM](https://user-images.githubusercontent.com/16284713/109864229-6d03f500-7c17-11eb-9ef0-3d52a3240105.png)

Test: https://dev.clin.iobio.io/
