### ISSUE TITLE
Search status dialog stuck for long time

### ISSUE THREAD

**Issue by adityaekawade** [iobio/clin.iobio#366]
From Matt - I tested a Mosaic project on stage using the URL trick and just copied/pasted the real clinical note in and have been stuck here on phenotype searching for 5+ min now , I eventually just closed it

![image (4)](https://user-images.githubusercontent.com/16284713/109547502-4b243a00-7a80-11eb-94a4-3385ad71fe08.png)

**Comment by adityaekawade** [comment]
Phenolyzer service can take a while to return the results for a new term. If it takes very long, we can allow the user to close the dialog but it will continue to load in the background and update the gene list once the data is returned. We can show a message, for example: "It is longer than expected, you can close this dialog box while the search is performed in the background. The gene list will be updated once the results are back". 

Genepanel also has the option to cancel the phenolyzer search if it was taking long, looks like that feature is missing here. I thought I had added it, but I will reintroduce it.

**Comment by mvelinder** [comment]
Agreed, I think the option to cancel or timeout and cancel it automatically would be good.

**Comment by adityaekawade** [comment]
The app will show a cancel button for phenolyzer search if it takes longer to fetch results. 
Test: https://dev.clin.iobio.io/
![Screen Shot 2021-03-08 at 3 40 03 PM](https://user-images.githubusercontent.com/16284713/110396598-25210b80-8025-11eb-988b-9e7d3ba066fa.png)
![Screen Shot 2021-03-08 at 3 41 00 PM](https://user-images.githubusercontent.com/16284713/110396599-25b9a200-8025-11eb-9df5-e047af03506e.png)

**Comment by adityaekawade** [comment]
You can also test this on genepanel using the following note: Treacher collins syndrome; ftt
