### ISSUE TITLE
Make modals more consistent

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/clin.iobio#379]
Once the user has picked some terms and the gene list is being generated, the modal could look more like the previous modal. E.g. titles in the same colours and remove the lines between terms. We can also keep the total number of terms for each resource visible. This way, if no terms were selected, we don't need to modify anything, it says no terms were selected and the rest of that resource column can be blank

![Asset 7](https://user-images.githubusercontent.com/523111/111220707-e7d1f600-85af-11eb-95a9-73dfde3d92c1.png)

**Comment by adityaekawade** [comment]
Test: 
https://genepanel.iobio.io/
https://dev.clin.iobio.io/

**Comment by AlistairNWard** [comment]
Looks great!
