### ISSUE TITLE
Clear save modal

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/clin.iobio#381]
Save a gene set to Mosaic, then change the genes and save another set. The save modal is still populated with the previous gene set details.

Clear the modal

**Comment by AlistairNWard** [comment]
Sorry this is a genepanel issue. We can discuss this. I'm guessing the modal remains populated so that you can "update" the currently saved analysis. Maybe what we need in the save modal is to make it clear whether the user wants to update currently saved analysis, or save a new analysis

**Comment by adityaekawade** [comment]
This is fixed in genepanel. Once a genelist is saved, the modal is cleared. Test https://genepanel.iobio.io/

**Comment by AlistairNWard** [comment]
What about if the user just wants to update a loaded analysis? I think we might need to serve both saving a new analysis and updating an existing loaded analysis (see my last comment)

**Comment by adityaekawade** [comment]
Yep, that needs to be updated in all our apps. Do you mind if I make it a new separate issue?  We can add radio buttons to either save it as a new analysis or update the current. It might require some work, so I think it will be better to address it as an independent issue. 

My comment was that modal gets cleared in genepanel now.

**Comment by AlistairNWard** [comment]
Of course. That would make sense
