### ISSUE TITLE
Fail to save set

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/clin.iobio#382]
Use the terms at the end of this issue. Create a gene set from just these HPO terms. Select the top 98 genes and try to save. The save fails.

My suspicion is that there is a gene in the list that is not in the Mosaic database, but we should investigate

Terms:
Nonimmune hydrops fetalis HP:0001790
Generalized edema HP:0007430
Lymphedema HP:0001004
Polyhydramnios HP:0001561
Bilateral pleural effusion HP:0002202
Pulmonary hypertension HP:0002092
Respiratory failure HP:0002878
Chylothorax HP:0010310
Thrombocytopenia HP:0001873
Hypoalbuminemia HP:0003073
Lymphedema HP:0001004
Lymphatic dysplasia HP:0100763

**Comment by adityaekawade** [comment]
Yes, your suspicion is right, there is an `IGH` gene that is not in the mosaic database. 
I copied the gene list from genepanel and tried to create a gene set from Mosaic and got the following error: 

![Screen Shot 2021-03-26 at 1 20 05 PM](https://user-images.githubusercontent.com/16284713/112688551-47dd5d80-8e36-11eb-9a90-6b5878364ea8.png)


I checked the documentation, I don't think I can bypass the gene which is not in the Mosaic DB when making a POST request. 
https://mosaic.chpc.utah.edu/api/#api-Genes-CreateGeneSet

**Comment by adityaekawade** [comment]
Hi @chmille4 , Is there a way we can bypass genes that are not in the Mosaic DB when making a post request to save a gene set? 
If you look at the example above, the POST request fails because `IGH` gene was not found. But if I try to add it from Mosaic UI, it shows an option to omit the invalid gene and proceed. Can this be done through API? So if a gene is not found bypass it but add the rest of the genes to the set?

**Comment by chmille4** [comment]
Hey @adityaekawade it is done client-side so you can't do it exactly via the API.

However, it should be pretty easy to replicate the client's functionality on your side. The backend returns the invalid genes, so you could just remove them then resend the request:`{"message":"No genes found with names: test","data":["test"]}`

**Comment by adityaekawade** [comment]
Thanks, @chmille4 that worked! 
@AlistairNWard I have pushed it to https://dev.panel.iobio.io/, you can test it with the URL trick by launching genepanel from the mosaic.

**Comment by AlistairNWard** [comment]
Yep, the saved set has 97 genes with the IGH gene removed.
