### ISSUE TITLE
Show reference genome

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/clin.iobio#388]
This goes for gene.iobio as well. When you are looking at the variants, nowhere is the reference listed. If you go to the files diaolog, the reference dropdown is not populated (which is another issue).

Gene.iobio should have the reference shown, and clin should have it throughout

**Comment by adityaekawade** [comment]
The reference dropdown used to be the default GRCH37 in gene.iobio, but we changed the behaviour to force users to select the correct reference based on their data.

**Comment by adityaekawade** [comment]
![Screen Shot 2021-03-29 at 2 11 53 PM](https://user-images.githubusercontent.com/16284713/113189910-957c1080-9210-11eb-820a-1104f3eb52a6.png)
The navbar will show the reference genome. Test: dev.clin  

Also, we had changed the behavior of the files dialog in gene.iobio to force the users to select the build for their data.
