### ISSUE TITLE
gene/clin tracking

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/clin.iobio#390]
Need to break down tracking for

1. How many people are using demo data vs their own data
2. Where are people launching gene/clin from? (Mosaic, Nebula, standalone)

**Comment by adityaekawade** [comment]
> How many people are using demo data vs their own data

I have added a new event category `data_type` for both gene and clin. This will allow us to track if the data is custom data or demo data. 

> Where are people launching gene/clin from? (Mosaic, Nebula, standalone)

For clin, I have added another event category `launch_type`. This will track if the app is launched in standalone mode or from Mosaic. 
For gene, it gets a little complex as there are various launches and referrals. Looking at the data obtained from Google Analytics, I think this is a good solution to track the launch modes: 
Acquisition > Referral shows all the launch points for gene (Mosaic, Nebula, MyGene2). It shows the numbers of Users and sessions for each source, along with the pages visited per session. 
From this data, we can calculate pageviews as Session * pages per session. 

The "Direct" channel shows the number of sessions where the user has directly visited gene.iobio which is basically the standalone mode. However, the clin hits are also considered in the direct channel as gene.iobio loads as iframe within clin. We can use filters to get exact hits for clin. 

Clin.iobio is now reporting the tracking and gene.iobio should also do the same in couple of days. 

Ref links: https://databox.com/what-is-pages-per-session-and-how-do-i-improve-it
https://databox.com/sessions-users-pageviews-in-google-analytics

**Comment by adityaekawade** [comment]
**Clin tracking:** 
Google analytics > Reports > Behvior > Event Category: 
<img width="1402" alt="Screen Shot 2021-04-07 at 10 23 00 AM" src="https://user-images.githubusercontent.com/16284713/113909157-36784780-978c-11eb-85e1-c46132668e42.png">


It is categorized into 3 categories: 
- `data_type` 
  - Demo Data 
  - Custom Data 
    - Config file 
    - Saved Analysis
- `launch_type`
  - Standalone 
  - Mosaic
- `select_phenotype_data`
  - Clinical note


**Gene tracking:** 
To find the users launching from Mosaic, Nebula, MyGene: 
Reports > Aquisition > Channels > Referrals: 
<img width="1383" alt="Screen Shot 2021-04-07 at 10 35 29 AM" src="https://user-images.githubusercontent.com/16284713/113910047-3e84b700-978d-11eb-96f1-4d45a69b1183.png">

The links does not show the URLs now (VCF, BAM, TBI, BAI)

To find the count of demo data vs custom data in standalone mode: 
Google analytics > Reports > Behvior > Event Category: 
- `data_type` 
  - Demo Data 
  - Custom Data

**Comment by AlistairNWard** [comment]
This is great. Thanks @adityaekawade!
