### ISSUE TITLE
Add GRCh38 bed

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/clin.iobio#392]
When adding your own data on clin launch, one of the steps requires a bed file to be selected. The options are GRCh37, or a custom bed, but there should be GRCh38 option available.

**Comment by adityaekawade** [comment]
@AlistairNWard There is already an option to add a bed file for GRCH38.  
![Screen Shot 2021-04-08 at 2 38 49 PM](https://user-images.githubusercontent.com/16284713/114099794-3f464780-9878-11eb-8964-4b13dbef9bf6.png)

**Comment by AlistairNWard** [comment]
Then it's the other way around! We need an option to add the GRCh37 bed.

**Comment by adityaekawade** [comment]
We also have the option to add a custom GRCh37 bed or select a default one. 
![Screen Shot 2021-04-08 at 4 03 16 PM](https://user-images.githubusercontent.com/16284713/114106622-08762e80-9884-11eb-8fb6-10bdbf6db2be.png)

We have the following options: 
For GRCH37: 
Exome - standard, custom 
Genome - No bed, standard, custom 

For GRCH38: 
Exome - standard, custom 
Genome - No bed, standard, custom 

I think we had covered all cases. Or did I miss something?

**Comment by AlistairNWard** [comment]
No, I think we're good. I think that I missed that the Exonic regions file changes based on the selected genome
