### ISSUE TITLE
Option to update or save as new analysis

### ISSUE THREAD

**Issue by adityaekawade** [iobio/clin.iobio#397]
The user should have an option to update or save it as a new analysis when launched a saved analysis from Mosaic. 
Radio buttons can be added for selecting these options.

**Comment by adityaekawade** [comment]
@AlistairNWard  I have added options to update a saved analysis or save it as a new analysis. You can test it on dev.clin. 

Adding the new analysis:
![Screen Shot 2021-04-16 at 4 02 30 PM](https://user-images.githubusercontent.com/16284713/115275845-2c910580-a0f7-11eb-870b-4a8da0393df7.png)

When launched from a saved analysis: 
Radio buttons are shown to either update it or save it as a new analysis. You can also update the title and description while updating a saved analysis.

![Screen Shot 2021-04-16 at 4 04 00 PM](https://user-images.githubusercontent.com/16284713/115275849-2d299c00-a0f7-11eb-8d60-c921f547c27e.png)
![Screen Shot 2021-04-16 at 4 04 12 PM](https://user-images.githubusercontent.com/16284713/115275850-2d299c00-a0f7-11eb-86ab-865c3a156e58.png)

**Comment by AlistairNWard** [comment]
Spot on!

**Comment by adityaekawade** [comment]
Oh. This feature was not pushed to prod. I will update prod now.
