### ISSUE TITLE
Deselect all - clinical note

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/clin.iobio#404]
Put in the clinical note and a bunch of terms are preselected. If I just want to work with HPO terms, I have to manually remove all other terms. Would be good to have a select all / deselect all check box for each source. Not sure how to style it though

![Asset 11](https://user-images.githubusercontent.com/523111/117701648-7e2c2d80-b195-11eb-994e-fef5792b19e2.png)

Make sure we have this everywhere it needs to be, e.g. in the genes table.

**Comment by adityaekawade** [comment]
Yes, I was thinking of having this option. It will be helpful even for me when I am testing. Right now I have to deselect everything to get HPO only list. This feature will definitely help save that time.

**Comment by AlistairNWard** [comment]
Put in the following note:

Cholestasis HP:0001396 Hyperbilirubinemia HP:0002904 Intrauterine growth retardation HP:0001511 Anemia HP:0001903 Neonatal alloimmune thrombocytopenia HP:0004809 Neutropenia HP:0001875 Hypotension HP:0002615 Neonatal sepsis HP:0040187 Respiratory distress HP:0002098

Choose to view terms from all sources:

<img width="1141" alt="Screen Shot 2021-07-02 at 1 26 39 PM" src="https://user-images.githubusercontent.com/523111/124309733-2e386a00-db39-11eb-8ab3-2988eb693787.png">

All terms are selected, but the toggles are not set to select all. So, to deselect all, you need to toggle to select all (which doesn't change anything), then toggle off all the terms

**Comment by adityaekawade** [comment]
This should be fixed. 
![Screen Shot 2021-07-02 at 2 08 10 PM](https://user-images.githubusercontent.com/16284713/124329309-17494600-db40-11eb-894b-77c57f8e04b2.png)

**Comment by AlistairNWard** [comment]
Fixed
