### ISSUE TITLE
Genepanel - HPO gene specificity chart should be continuous

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/clin.iobio#412]
Instead of a histogram, use a continuous chart as the brushing is continuous.

**Comment by adityaekawade** [comment]
Any preference for a line chart or area chart? @AlistairNWard 

![Screen Shot 2021-06-28 at 11 03 08 AM](https://user-images.githubusercontent.com/16284713/123683124-b26cb380-d800-11eb-88de-fd0f4dbb9651.png)
![Screen Shot 2021-06-28 at 11 04 16 AM](https://user-images.githubusercontent.com/16284713/123683127-b39de080-d800-11eb-88fb-ce1c01885368.png)

**Comment by adityaekawade** [comment]
I have currently updated it with the area chart on dev.panel.
