### ISSUE TITLE
Make case summary editable

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/clin.iobio#422]
Ultimately, we should allow 2 options for the case summary:
1. It is imported from Mosaic,
2. It is manually entered.

I propose:
- [ ] On the Report page, make the case summary a card consistent with the other gene panel styling
- [ ] Allow the user to edit the summary directly
- [ ] Allow the user to connect to a Mosaic attribute
- [ ] If the case summary is updated, the Review case is also updated

![Asset 13](https://user-images.githubusercontent.com/523111/127178736-fa5d8880-4b54-4b2a-a8b4-cda18fbca4ad.png)

**Comment by adityaekawade** [comment]
Reference to another issue about clinical summary: https://github.com/iobio/clin.iobio/issues/369
