### ISSUE TITLE
Gene panel HPO help messages

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/clin.iobio#425]
1. I've included figures, but let's make sure the styling is where we want it before adding to the help
2. Make sure the axis titles are centred. They don't appear to be on the specificity chart

**HPO overlap**
Title: Overlapping HPO terms
X-axis title: Genes
Y-axis title: User-defined HPO terms
Help text: The number of genes that overlap a specific number of user-defined HPO terms. For example, the bar with a value of 1 represents how many returned genes overlap exactly 1 HPO term. To update the gene list to only include genes that overlap at least 3 HPO terms, drag on the chart as shown below:

![Screen Shot 2021-07-28 at 9 48 24 AM](https://user-images.githubusercontent.com/523111/127333656-bc34158f-121a-4635-acaf-f085048ed4b0.png)

**Specificity**
Title: Specificity score
X-axis title: Specificity score
Y-axis title: Genes
Help text: The specificity score is calculated as the the number of HPO (I CAN'T REMEMBER THE EXACT DEFINITION!). The lower the score, the more HPO terms this gene is associated with, and consequently, it is less likely to have a strong association. Dragging on the chart will update the gene list to include only those with scores in the specified range:

![Screen Shot 2021-07-28 at 9 55 48 AM](https://user-images.githubusercontent.com/523111/127334758-861d7b07-6ac8-42a7-9da3-254bb21882f7.png)

The gene modal includes both a specificity score and a scaled score. Remind me what the difference is? Should we be providing 2 scores?

**Comment by adityaekawade** [comment]
Test: https://dev.clin.iobio.io/
This is a hover-over tooltip. Is this ok or should we have a modal that opens up when the help icon is clicked to show the help message?

**Comment by AlistairNWard** [comment]
1. Typically the text on the y-axis label reads up the axis, so I would rotate the y-axis labels
2. It would probably nice to have a title in the help modals - e.g. just the graph title
3. I think the explanation of how the specificity score is confusing. We probably don't need to be so specific. Maybe we just say "It is a scaled score between zero and one that is proportional to the number of HPO terms the gene is associated with. The lower the score..."

**Comment by AlistairNWard** [comment]
1. I meant the text on the y-axis should be rotated 180 degrees, so it read upwards not downwards.

**Comment by adityaekawade** [comment]
I thought you meant to rotate it so the text becomes horizontal. Also the text "User-defined HPO terms" is long so it's taking the length of entire Y-axis to fit it. That's why I had rotated it this way. 
I will rotate it 180 degrees from what I had initially so the text reads upwards.

**Comment by AlistairNWard** [comment]
Sorry, I didn't make it clear! If we do it horizontal, that is unusual, and also takes a lot of horizontal space away from the chart. I think it's common if the name gets too long to just put what fits and put an ellipsis at the end. E.g. this is a Google Sheet chart:

![Screen Shot 2021-09-01 at 10 46 58 AM](https://user-images.githubusercontent.com/523111/131692882-ee36d194-ba58-459a-93c9-c99e8400218b.png)

**Comment by AlistairNWard** [comment]
We could also change the axis title to 'Entered HPO terms' which is a bit shorter

**Comment by adityaekawade** [comment]
Agree,the horizontal text is taking a lot of space. 
The above example from Google chart makes it clear.

**Comment by adityaekawade** [comment]
Rotated the text 180 deg on Y-Axis
Test: https://dev.panel.iobio.io/
![Screen Shot 2021-09-01 at 10 25 16 AM](https://user-images.githubusercontent.com/16284713/131716223-fefbdf64-1738-49f9-ad70-3f3df03f7f5f.png)
