### ISSUE TITLE
Launch clin.iobio from Mosaic

### ISSUE THREAD

**Issue by tonydisera** [iobio/clin.iobio#43]

**Comment by AlistairNWard** [comment]
This is already implemented. We have settings on the apps to ensure that not all apps are viewable by all users or all projects (with an intent to keep dev tools hidden from production audience, for example). We should make sure we have these settings correct for the Utah instance though.

**Comment by tonydisera** [comment]
Hi Al,

I should have worded this more succinctly.  This was a reminder for me to change the clin.iobio.io code to worked with the new Mosaic parameters (project id + sample id).  But that does raise a good question.  What version of the local install of Mosaic are we running? 

Tony
